const drugs = [
  // Analgesics
  { name: 'Paracetamol', genericName: 'Acetaminophen', category: 'Analgesic/Antipyretic', dosages: ['500mg', '650mg', '1g'], routes: ['Oral', 'IV', 'PR'], sideEffects: ['Nausea', 'Rash', 'Liver toxicity (overdose)'], indications: ['Fever', 'Mild to moderate pain', 'Headache'], contraindications: ['Severe liver disease', 'Alcoholism'], nursingConsiderations: ['Monitor liver function with prolonged use', 'Do not exceed 4g daily', 'Antidote: N-acetylcysteine for overdose'] },
  { name: 'Ibuprofen', genericName: 'Ibuprofen', category: 'NSAID', dosages: ['200mg', '400mg', '600mg', '800mg'], routes: ['Oral', 'IV'], sideEffects: ['GI upset', 'Bleeding risk', 'Renal impairment'], indications: ['Pain', 'Inflammation', 'Fever', 'Dysmenorrhea'], contraindications: ['Peptic ulcer', 'Severe renal disease', 'Asthma (sensitive)'], nursingConsiderations: ['Take with food or milk', 'Monitor renal function', 'Avoid in dehydration'] },
  { name: 'Diclofenac', genericName: 'Diclofenac Sodium', category: 'NSAID', dosages: ['50mg', '75mg', '100mg'], routes: ['Oral', 'IM', 'Topical'], sideEffects: ['GI bleeding', 'Hypertension', 'Edema'], indications: ['Arthritis', 'Acute pain', 'Musculoskeletal pain'], contraindications: ['Peptic ulcer', 'Severe heart failure', 'Third trimester pregnancy'], nursingConsiderations: ['Use lowest effective dose', 'Monitor BP', 'Avoid with anticoagulants'] },
  { name: 'Naproxen', genericName: 'Naproxen', category: 'NSAID', dosages: ['250mg', '500mg', '750mg'], routes: ['Oral'], sideEffects: ['Heartburn', 'Drowsiness', 'Constipation'], indications: ['Rheumatoid arthritis', 'Osteoarthritis', 'Ankylosing spondylitis'], contraindications: ['Aspirin allergy', 'Recent CABG'], nursingConsiderations: ['Monitor for GI bleeding', 'Use with caution in elderly'] },
  { name: 'Pentazocine', genericName: 'Pentazocine', category: 'Opioid Analgesic', dosages: ['30mg', '50mg'], routes: ['Oral', 'IM', 'IV'], sideEffects: ['Sedation', 'Dizziness', 'Nausea', 'Hallucinations'], indications: ['Moderate to severe pain'], contraindications: ['Head injury', 'Respiratory depression'], nursingConsiderations: ['Monitor respiratory rate', 'Can cause withdrawal in opioid-dependent patients'] },
  { name: 'Tramadol', genericName: 'Tramadol', category: 'Opioid Analgesic', dosages: ['50mg', '100mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Nausea', 'Dizziness', 'Seizures (high dose)', 'Constipation'], indications: ['Moderate to severe pain'], contraindications: ['Seizure disorder', 'MAOI use', 'Suicidal risk'], nursingConsiderations: ['Monitor for serotonin syndrome', 'Lower dose in elderly', 'Do not crush SR tablets'] },
  { name: 'Pethidine', genericName: 'Meperidine', category: 'Opioid Analgesic', dosages: ['50mg', '100mg'], routes: ['Oral', 'IM', 'IV'], sideEffects: ['Nausea', 'Dizziness', 'Seizures (with repeated use)', 'Constipation'], indications: ['Moderate to severe pain', 'Post-operative pain'], contraindications: ['MAOI use', 'Seizure disorder', 'Renal impairment'], nursingConsiderations: ['Avoid repeated use (normeperidine accumulation)', 'Monitor respiratory depression', 'Not recommended for chronic pain'] },
  { name: 'Morphine', genericName: 'Morphine Sulfate', category: 'Opioid Analgesic', dosages: ['5mg', '10mg', '15mg', '30mg'], routes: ['Oral', 'IV', 'IM', 'SC'], sideEffects: ['Respiratory depression', 'Constipation', 'Sedation', 'Nausea', 'Pruritus'], indications: ['Severe pain', 'Acute myocardial infarction', 'Post-operative pain'], contraindications: ['Respiratory depression', 'Head injury', 'Paralytic ileus'], nursingConsiderations: ['Monitor respiratory rate closely', 'Naloxone is antidote', 'Avoid alcohol and CNS depressants'] },
  { name: 'Fentanyl', genericName: 'Fentanyl', category: 'Opioid Analgesic', dosages: ['25mcg', '50mcg', '100mcg'], routes: ['IV', 'Transdermal', 'Buccal', 'Intranasal'], sideEffects: ['Respiratory depression', 'Bradycardia', 'Chest wall rigidity'], indications: ['Severe pain', 'Anesthesia adjunct', 'Chronic pain'], contraindications: ['Opioid-naive patients (transdermal)', 'Respiratory depression'], nursingConsiderations: ['Monitor for chest wall rigidity with rapid IV', 'Wear gloves for transdermal handling'] },

  // Antibiotics
  { name: 'Amoxicillin', genericName: 'Amoxicillin', category: 'Antibiotic (Penicillin)', dosages: ['250mg', '500mg', '875mg'], routes: ['Oral', 'IV'], sideEffects: ['Diarrhea', 'Rash', 'Nausea'], indications: ['Bacterial infections', 'UTI', 'Respiratory infections', 'Otitis media'], contraindications: ['Penicillin allergy'], nursingConsiderations: ['Take with food to reduce GI upset', 'Complete full course', 'Monitor for rash'] },
  { name: 'Amoxicillin-Clavulanate', genericName: 'Co-amoxiclav', category: 'Antibiotic (Penicillin)', dosages: ['250/125mg', '500/125mg', '875/125mg'], routes: ['Oral', 'IV'], sideEffects: ['Diarrhea', 'Rash', 'Nausea', 'Hepatitis'], indications: ['Sinusitis', 'Pneumonia', 'Animal bites', 'UTI'], contraindications: ['Penicillin allergy', 'Previous jaundice with co-amoxiclav'], nursingConsiderations: ['Take with food', 'Monitor LFTs with prolonged use'] },
  { name: 'Ampicillin', genericName: 'Ampicillin', category: 'Antibiotic (Penicillin)', dosages: ['250mg', '500mg', '1g', '2g'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Rash', 'Diarrhea', 'Nausea'], indications: ['UTI', 'Meningitis', 'Respiratory infections', 'GI infections'], contraindications: ['Penicillin allergy'], nursingConsiderations: ['Administer IV slowly over 3-5 min', 'Monitor for rashes (especially in mononucleosis)'] },
  { name: 'Ceftriaxone', genericName: 'Ceftriaxone', category: 'Antibiotic (Cephalosporin)', dosages: ['250mg', '500mg', '1g', '2g'], routes: ['IV', 'IM'], sideEffects: ['Diarrhea', 'Rash', 'Biliary sludge'], indications: ['Pneumonia', 'Meningitis', 'Gonorrhea', 'Sepsis'], contraindications: ['Cephalosporin allergy', 'Neonates with hyperbilirubinemia'], nursingConsiderations: ['Do not mix with calcium-containing solutions', 'Monitor injection site', 'IM: dilute with lidocaine'] },
  { name: 'Cefixime', genericName: 'Cefixime', category: 'Antibiotic (Cephalosporin)', dosages: ['200mg', '400mg'], routes: ['Oral'], sideEffects: ['Diarrhea', 'Nausea', 'Abdominal pain'], indications: ['UTI', 'Gonorrhea', 'Typhoid fever', 'Respiratory infections'], contraindications: ['Cephalosporin allergy'], nursingConsiderations: ['Monitor for pseudomembranous colitis', 'Take with food to reduce GI upset'] },
  { name: 'Cefuroxime', genericName: 'Cefuroxime', category: 'Antibiotic (Cephalosporin)', dosages: ['250mg', '500mg', '750mg', '1.5g'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Diarrhea', 'Rash', 'Injection site pain'], indications: ['RTI', 'UTI', 'Skin infections', 'Surgical prophylaxis'], contraindications: ['Cephalosporin allergy'], nursingConsiderations: ['Administer with food', 'Monitor renal function'] },
  { name: 'Metronidazole', genericName: 'Metronidazole', category: 'Antibiotic/Antiprotozoal', dosages: ['200mg', '400mg', '500mg'], routes: ['Oral', 'IV', 'Topical', 'PR'], sideEffects: ['Metallic taste', 'Nausea', 'Headache', 'Dizziness'], indications: ['Anaerobic infections', 'Trichomoniasis', 'Bacterial vaginosis', 'Giardiasis'], contraindications: ['First trimester pregnancy (avoid if possible)'], nursingConsiderations: ['Avoid alcohol during treatment', 'May cause dark urine', 'Monitor for neuropathy with prolonged use'] },
  { name: 'Azithromycin', genericName: 'Azithromycin', category: 'Antibiotic (Macrolide)', dosages: ['250mg', '500mg', '1g'], routes: ['Oral', 'IV'], sideEffects: ['Nausea', 'Diarrhea', 'Abdominal pain', 'QT prolongation'], indications: ['RTI', 'STIs', 'Skin infections', 'Mycobacterium avium'], contraindications: ['Macrolide allergy', 'QT prolongation'], nursingConsiderations: ['Take on empty stomach or with food', 'Monitor ECG with pre-existing QT prolongation'] },
  { name: 'Erythromycin', genericName: 'Erythromycin', category: 'Antibiotic (Macrolide)', dosages: ['250mg', '500mg'], routes: ['Oral', 'IV', 'Topical'], sideEffects: ['GI upset', 'QT prolongation', 'Hearing loss (high dose)'], indications: ['Respiratory infections', 'Pertussis', 'Acne vulgaris', 'Prokinetic agent'], contraindications: ['Hepatic impairment', 'Macrolide allergy'], nursingConsiderations: ['Administer with full glass of water', 'Monitor hearing with high doses', 'May increase theophylline levels'] },
  { name: 'Clarithromycin', genericName: 'Clarithromycin', category: 'Antibiotic (Macrolide)', dosages: ['250mg', '500mg'], routes: ['Oral', 'IV'], sideEffects: ['Nausea', 'Diarrhea', 'Dysgeusia', 'QT prolongation'], indications: ['Respiratory infections', 'H. pylori', 'Skin infections'], contraindications: ['Macrolide allergy', 'QT prolongation'], nursingConsiderations: ['Take with or without food', 'Avoid with statins (increases statin levels)'] },
  { name: 'Ciprofloxacin', genericName: 'Ciprofloxacin', category: 'Antibiotic (Fluoroquinolone)', dosages: ['250mg', '500mg', '750mg'], routes: ['Oral', 'IV', 'Ophthalmic', 'Otic'], sideEffects: ['Nausea', 'Tendonitis', 'QT prolongation', 'CNS effects'], indications: ['UTI', 'GI infections', 'Respiratory infections', 'Anthrax'], contraindications: ['Children (avoid)', 'Pregnancy', 'Tendon disorders'], nursingConsiderations: ['Avoid antacids within 2 hours', 'Hydrate well', 'Monitor for tendon pain', 'Avoid excessive sun exposure'] },
  { name: 'Levofloxacin', genericName: 'Levofloxacin', category: 'Antibiotic (Fluoroquinolone)', dosages: ['250mg', '500mg', '750mg'], routes: ['Oral', 'IV', 'Ophthalmic'], sideEffects: ['Nausea', 'Tendon rupture', 'QT prolongation', 'Peripheral neuropathy'], indications: ['Pneumonia', 'UTI', 'Prostatitis', 'Skin infections'], contraindications: ['Fluoroquinolone allergy', 'Tendon disorders', 'Myasthenia gravis'], nursingConsiderations: ['Monitor blood glucose', 'Avoid sun exposure', 'Hydrate well'] },
  { name: 'Doxycycline', genericName: 'Doxycycline', category: 'Antibiotic (Tetracycline)', dosages: ['50mg', '100mg'], routes: ['Oral', 'IV'], sideEffects: ['Photosensitivity', 'GI upset', 'Esophagitis', 'Tooth discoloration'], indications: ['Acne', 'Malaria prophylaxis', 'RTI', 'Cholera', 'Rickettsial infections'], contraindications: ['Children <8 years', 'Pregnancy', 'Tetracycline allergy'], nursingConsiderations: ['Take with full glass of water', 'Avoid lying down for 30 min after dose', 'Use sun protection'] },
  { name: 'Gentamicin', genericName: 'Gentamicin', category: 'Antibiotic (Aminoglycoside)', dosages: ['80mg', '120mg', '160mg'], routes: ['IV', 'IM', 'Topical', 'Ophthalmic'], sideEffects: ['Nephrotoxicity', 'Ototoxicity', 'Neuromuscular blockade'], indications: ['Gram-negative infections', 'Sepsis', 'Surgical prophylaxis'], contraindications: ['Myasthenia gravis', 'Aminoglycoside allergy'], nursingConsiderations: ['Monitor peak and trough levels', 'Monitor renal function', 'Assess hearing', 'Hydrate well'] },
  { name: 'Cloxacillin', genericName: 'Cloxacillin', category: 'Antibiotic (Penicillinase-resistant)', dosages: ['250mg', '500mg', '1g'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Rash', 'Diarrhea', 'Nausea'], indications: ['Staphylococcal infections', 'Cellulitis', 'Bone infections'], contraindications: ['Penicillin allergy'], nursingConsiderations: ['Take on empty stomach', 'Monitor for superinfection'] },
  { name: 'Nitrofurantoin', genericName: 'Nitrofurantoin', category: 'Antibiotic (Urinary)', dosages: ['50mg', '100mg'], routes: ['Oral'], sideEffects: ['Nausea', 'Brown urine', 'Pulmonary fibrosis (chronic)'], indications: ['UTI', 'UTI prophylaxis'], contraindications: ['Renal impairment', 'Pregnancy (term)', 'G6PD deficiency'], nursingConsiderations: ['Take with food', 'May discolor urine brown', 'Monitor pulmonary symptoms with prolonged use'] },
  { name: 'Cotrimoxazole', genericName: 'Trimethoprim-Sulfamethoxazole', category: 'Antibiotic (Sulfonamide)', dosages: ['80/400mg', '160/800mg', '400/80mg per 5ml'], routes: ['Oral', 'IV'], sideEffects: ['Rash', 'Photosensitivity', 'Hyperkalemia', 'Stevens-Johnson syndrome'], indications: ['UTI', 'Pneumocystis pneumonia', 'RTI', 'Typhoid'], contraindications: ['Sulfa allergy', 'Pregnancy', 'Severe hepatic/renal disease', 'G6PD deficiency'], nursingConsiderations: ['Monitor for rash (may progress to SJS)', 'Encourage fluid intake', 'Monitor potassium and renal function'] },

  // Antimalarials
  { name: 'Artemether-Lumefantrine', genericName: 'Artemether/Lumefantrine', category: 'Antimalarial', dosages: ['20/120mg', '40/240mg', '80/480mg'], routes: ['Oral'], sideEffects: ['Headache', 'Dizziness', 'Nausea', 'Weakness', 'Cough'], indications: ['Uncomplicated malaria'], contraindications: ['Severe malaria (use IV artesunate)', 'Pregnancy (first trimester)'], nursingConsiderations: ['Take with fatty food to improve absorption', 'Complete 3-day course', 'Repeat dose if vomiting within 1 hour'] },
  { name: 'Artesunate', genericName: 'Artesunate', category: 'Antimalarial', dosages: ['60mg', '120mg', '240mg'], routes: ['IV', 'IM', 'PR'], sideEffects: ['Delayed hemolytic anemia', 'Nausea', 'Dizziness'], indications: ['Severe malaria', 'Cerebral malaria'], contraindications: ['Artesunate allergy'], nursingConsiderations: ['Monitor for hemolytic anemia 1-3 weeks after treatment', 'Administer slowly IV', 'Prepare fresh solution'] },
  { name: 'Chloroquine', genericName: 'Chloroquine Phosphate', category: 'Antimalarial', dosages: ['150mg base', '300mg base'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Pruritus', 'Nausea', 'Headache', 'Retinopathy (long-term)'], indications: ['Malaria (sensitive strains)', 'Amebiasis', 'Rheumatoid arthritis'], contraindications: ['Retinopathy', 'Porphyria'], nursingConsiderations: ['Monitor vision with long-term use', 'Can cause severe pruritus in dark-skinned patients'] },
  { name: 'Quinine', genericName: 'Quinine', category: 'Antimalarial', dosages: ['300mg', '600mg'], routes: ['Oral', 'IV'], sideEffects: ['Cinchonism (tinnitus, headache)', 'Hypoglycemia', 'QT prolongation'], indications: ['Severe malaria', 'Chloroquine-resistant malaria'], contraindications: ['G6PD deficiency', 'QT prolongation', 'Tinnitus'], nursingConsiderations: ['Monitor blood glucose', 'Monitor ECG', 'Avoid grapefruit juice'] },
  { name: 'Sulfadoxine-Pyrimethamine', genericName: 'Sulfadoxine/Pyrimethamine', category: 'Antimalarial', dosages: ['500/25mg'], routes: ['Oral'], sideEffects: ['Rash', 'Stevens-Johnson syndrome', 'Anemia'], indications: ['Malaria prophylaxis (pregnancy - IPTp)', 'Chloroquine-resistant malaria'], contraindications: ['Sulfa allergy', 'Pregnancy (first trimester)', 'G6PD deficiency'], nursingConsiderations: ['Used for intermittent preventive treatment in pregnancy', 'Monitor for severe skin reactions'] },
  { name: 'Primaquine', genericName: 'Primaquine', category: 'Antimalarial', dosages: ['7.5mg', '15mg'], routes: ['Oral'], sideEffects: ['Hemolytic anemia (G6PD)', 'Nausea', 'Abdominal cramps'], indications: ['Radical cure of P. vivax and P. ovale', 'Malaria prophylaxis'], contraindications: ['G6PD deficiency', 'Pregnancy', 'Lupus erythematosus'], nursingConsiderations: ['Must test G6PD before use', 'Monitor for hemolysis', 'Take with food'] },

  // Antihypertensives
  { name: 'Nifedipine', genericName: 'Nifedipine', category: 'Antihypertensive (Calcium Channel Blocker)', dosages: ['10mg', '20mg', '30mg', '60mg'], routes: ['Oral', 'Sublingual'], sideEffects: ['Flushing', 'Headache', 'Dizziness', 'Peripheral edema'], indications: ['Hypertension', 'Angina pectoris', 'Raynaud phenomenon'], contraindications: ['Severe hypotension', 'Aortic stenosis'], nursingConsiderations: ['Avoid sublingual use (rapid hypotension)', 'Monitor BP and HR', 'Check for ankle edema'] },
  { name: 'Amlodipine', genericName: 'Amlodipine', category: 'Antihypertensive (Calcium Channel Blocker)', dosages: ['2.5mg', '5mg', '10mg'], routes: ['Oral'], sideEffects: ['Peripheral edema', 'Flushing', 'Palpitations', 'Fatigue'], indications: ['Hypertension', 'Chronic stable angina'], contraindications: ['Severe hypotension'], nursingConsiderations: ['Monitor BP regularly', 'Check for gingival hyperplasia', 'Report palpitations'] },
  { name: 'Enalapril', genericName: 'Enalapril', category: 'ACE Inhibitor', dosages: ['2.5mg', '5mg', '10mg', '20mg'], routes: ['Oral', 'IV'], sideEffects: ['Cough', 'Hyperkalemia', 'Angioedema', 'Hypotension'], indications: ['Hypertension', 'Heart failure', 'Diabetic nephropathy'], contraindications: ['Pregnancy', 'Bilateral renal artery stenosis', 'History of angioedema'], nursingConsiderations: ['Monitor BP and renal function', 'Monitor potassium levels', 'Avoid K supplements', 'Report cough'] },
  { name: 'Lisinopril', genericName: 'Lisinopril', category: 'ACE Inhibitor', dosages: ['2.5mg', '5mg', '10mg', '20mg', '40mg'], routes: ['Oral'], sideEffects: ['Dry cough', 'Hyperkalemia', 'Hypotension', 'Angioedema'], indications: ['Hypertension', 'Heart failure', 'MI'], contraindications: ['Pregnancy', 'Angioedema history'], nursingConsiderations: ['Monitor renal function', 'Monitor BP', 'Check potassium'] },
  { name: 'Losartan', genericName: 'Losartan', category: 'ARB', dosages: ['25mg', '50mg', '100mg'], routes: ['Oral'], sideEffects: ['Dizziness', 'Hyperkalemia', 'Hypotension'], indications: ['Hypertension', 'Diabetic nephropathy', 'Heart failure'], contraindications: ['Pregnancy', 'Bilateral renal artery stenosis'], nursingConsiderations: ['Monitor BP and potassium', 'Hydrate well', 'Avoid K supplements'] },
  { name: 'Methyldopa', genericName: 'Methyldopa', category: 'Antihypertensive (Central Alpha Agonist)', dosages: ['250mg', '500mg'], routes: ['Oral', 'IV'], sideEffects: ['Sedation', 'Dry mouth', 'Positive Coombs test', 'Depression'], indications: ['Hypertension in pregnancy', 'Chronic hypertension'], contraindications: ['Liver disease', 'Depression', 'Pheochromocytoma'], nursingConsiderations: ['Monitor liver function', 'May cause positive Coombs test', 'Monitor BP and HR'] },
  { name: 'Hydralazine', genericName: 'Hydralazine', category: 'Vasodilator', dosages: ['25mg', '50mg', '100mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Headache', 'Flushing', 'Palpitations', 'Lupus syndrome (prolonged)'], indications: ['Hypertension', 'Heart failure', 'Hypertensive urgency'], contraindications: ['Lupus erythematosus', 'Severe tachycardia'], nursingConsiderations: ['Monitor BP closely with IV use', 'Monitor for lupus-like symptoms', 'Give with beta-blocker to reduce reflex tachycardia'] },
  { name: 'Propranolol', genericName: 'Propranolol', category: 'Beta Blocker', dosages: ['10mg', '20mg', '40mg', '80mg'], routes: ['Oral', 'IV'], sideEffects: ['Bradycardia', 'Bronchospasm', 'Fatigue', 'Cold extremities', 'Mask hypoglycemia'], indications: ['Hypertension', 'Angina', 'Migraine prophylaxis', 'Thyrotoxicosis', 'Essential tremor'], contraindications: ['Asthma', 'Heart block', 'Bradycardia', 'COPD'], nursingConsiderations: ['Do not stop abruptly (rebound tachycardia)', 'Monitor HR and BP', 'Caution in diabetes (masks hypoglycemia)'] },
  { name: 'Atenolol', genericName: 'Atenolol', category: 'Beta Blocker (Cardioselective)', dosages: ['25mg', '50mg', '100mg'], routes: ['Oral', 'IV'], sideEffects: ['Bradycardia', 'Fatigue', 'Cold extremities'], indications: ['Hypertension', 'Angina', 'Post-MI'], contraindications: ['Asthma', 'Heart block', 'Bradycardia'], nursingConsiderations: ['Do not stop abruptly', 'Monitor HR and BP', 'Caution in diabetes'] },
  { name: 'Furosemide', genericName: 'Furosemide', category: 'Diuretic (Loop)', dosages: ['20mg', '40mg', '80mg', '120mg', '500mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Hypokalemia', 'Dehydration', 'Ototoxicity (high dose)', 'Hyperglycemia'], indications: ['Hypertension', 'Heart failure', 'Pulmonary edema', 'Renal impairment'], contraindications: ['Anuria', 'Severe hypokalemia', 'Sulfa allergy (cross-reaction)'], nursingConsiderations: ['Monitor potassium and other electrolytes', 'Monitor I/O and weight', 'Administer IV slowly over 1-2 min', 'Ototoxic with aminoglycosides'] },
  { name: 'Hydrochlorothiazide', genericName: 'Hydrochlorothiazide (HCTZ)', category: 'Diuretic (Thiazide)', dosages: ['12.5mg', '25mg', '50mg'], routes: ['Oral'], sideEffects: ['Hypokalemia', 'Hyperglycemia', 'Hyperuricemia', 'Photosensitivity'], indications: ['Hypertension', 'Edema'], contraindications: ['Anuria', 'Sulfa allergy', 'Severe renal impairment'], nursingConsiderations: ['Monitor electrolytes and glucose', 'Take in morning to avoid nocturia', 'May precipitate gout'] },
  { name: 'Spironolactone', genericName: 'Spironolactone', category: 'Diuretic (Potassium-sparing)', dosages: ['25mg', '50mg', '100mg'], routes: ['Oral'], sideEffects: ['Hyperkalemia', 'Gynecomastia', 'Menstrual irregularities'], indications: ['Heart failure', 'Hypertension', 'Ascites', 'Hyperaldosteronism'], contraindications: ['Hyperkalemia', 'Renal failure', 'Addison disease'], nursingConsiderations: ['Monitor potassium closely', 'Avoid K supplements', 'Monitor for gynecomastia'] },
  { name: 'Mannitol', genericName: 'Mannitol', category: 'Diuretic (Osmotic)', dosages: ['20% solution', '25% solution'], routes: ['IV'], sideEffects: ['Electrolyte imbalance', 'Dehydration', 'Pulmonary edema', 'Headache'], indications: ['Cerebral edema', 'Raised ICP', 'Acute renal failure (early)'], contraindications: ['Anuria', 'Heart failure', 'Pulmonary edema'], nursingConsiderations: ['Monitor I/O and electrolytes', 'Check for crystallisation in solution', 'Use filter needle'] },

  // Anticoagulants & Antiplatelets
  { name: 'Warfarin', genericName: 'Warfarin Sodium', category: 'Anticoagulant', dosages: ['1mg', '2mg', '3mg', '5mg'], routes: ['Oral'], sideEffects: ['Bleeding', 'Bruising', 'Skin necrosis', 'Purple toes syndrome'], indications: ['Atrial fibrillation', 'DVT', 'PE', 'Mechanical heart valves'], contraindications: ['Active bleeding', 'Pregnancy', 'Severe liver disease'], nursingConsiderations: ['Monitor INR (target 2-3 for most indications)', 'Monitor for bleeding', 'Vitamin K is antidote', 'Beware drug interactions'] },
  { name: 'Heparin', genericName: 'Unfractionated Heparin', category: 'Anticoagulant', dosages: ['5000U', '7500U', '10000U'], routes: ['IV', 'SC'], sideEffects: ['Bleeding', 'Heparin-induced thrombocytopenia (HIT)', 'Osteoporosis (long-term)'], indications: ['DVT/PE treatment and prophylaxis', 'ACS', 'Dialysis'], contraindications: ['Active bleeding', 'HIT history', 'Thrombocytopenia'], nursingConsiderations: ['Monitor aPTT (1.5-2.5x control)', 'Monitor platelets (HIT)', 'Protamine sulfate is antidote'] },
  { name: 'Enoxaparin', genericName: 'Enoxaparin (LMWH)', category: 'Anticoagulant', dosages: ['20mg', '40mg', '60mg', '80mg', '100mg'], routes: ['SC'], sideEffects: ['Bleeding', 'Thrombocytopenia (less than heparin)'], indications: ['DVT/PE prophylaxis', 'ACS', 'DVT/PE treatment'], contraindications: ['Active bleeding', 'HIT history', 'Severe renal impairment'], nursingConsiderations: ['Do not expel air bubble from syringe', 'Rotate injection sites', 'Protamine partial reversal'] },
  { name: 'Aspirin', genericName: 'Acetylsalicylic Acid', category: 'Antiplatelet/NSAID', dosages: ['75mg', '150mg', '300mg', '600mg', '900mg'], routes: ['Oral', 'PR'], sideEffects: ['GI bleeding', 'Reye syndrome (children)', 'Tinnitus'], indications: ['MI prophylaxis', 'Stroke prophylaxis', 'Pain', 'Fever'], contraindications: ['Active peptic ulcer', 'Aspirin allergy', 'Children with viral illness', 'G6PD deficiency'], nursingConsiderations: ['Give with food', 'Low dose (75mg) for antiplatelet effect', 'Avoid in children with fever'] },
  { name: 'Clopidogrel', genericName: 'Clopidogrel', category: 'Antiplatelet', dosages: ['75mg', '300mg (loading)'], routes: ['Oral'], sideEffects: ['Bleeding', 'Thrombotic thrombocytopenic purpura (rare)'], indications: ['ACS', 'Stroke prophylaxis', 'Post-stent'], contraindications: ['Active bleeding', 'Severe liver disease'], nursingConsiderations: ['Loading dose of 300mg for ACS', 'Monitor for bleeding', 'Used with aspirin in ACS'] },

  // Anticonvulsants
  { name: 'Diazepam', genericName: 'Diazepam', category: 'Anticonvulsant/Benzodiazepine', dosages: ['2mg', '5mg', '10mg'], routes: ['Oral', 'IV', 'PR', 'IM'], sideEffects: ['Sedation', 'Respiratory depression', 'Dizziness', 'Dependence'], indications: ['Status epilepticus (IV/PR)', 'Anxiety', 'Muscle spasms', 'Alcohol withdrawal'], contraindications: ['Severe respiratory insufficiency', 'Myasthenia gravis', 'Narrow-angle glaucoma'], nursingConsiderations: ['Monitor respiratory rate when given IV', 'PR: use only rectal tube', 'Avoid abrupt withdrawal'] },
  { name: 'Phenytoin', genericName: 'Phenytoin Sodium', category: 'Anticonvulsant', dosages: ['50mg', '100mg', '250mg/5ml'], routes: ['Oral', 'IV'], sideEffects: ['Gingival hyperplasia', 'Ataxia', 'Nystagmus', 'Rash', 'Stevens-Johnson syndrome'], indications: ['Tonic-clonic seizures', 'Partial seizures', 'Status epilepticus'], contraindications: ['Sinus bradycardia', 'AV block'], nursingConsiderations: ['Monitor serum levels (10-20 mcg/mL)', 'IV: give slowly, compatible only with NS', 'Good oral hygiene for gingival hyperplasia'] },
  { name: 'Carbamazepine', genericName: 'Carbamazepine', category: 'Anticonvulsant', dosages: ['100mg', '200mg', '400mg'], routes: ['Oral'], sideEffects: ['Dizziness', 'Diplopia', 'Hyponatremia', 'Stevens-Johnson syndrome', 'Bone marrow suppression'], indications: ['Partial seizures', 'Generalized tonic-clonic', 'Trigeminal neuralgia', 'Bipolar disorder'], contraindications: ['AV block', 'Bone marrow depression', 'MAOI use'], nursingConsiderations: ['Monitor CBC and LFTs', 'Monitor sodium levels', 'Many drug interactions (CYP3A4 inducer)'] },
  { name: 'Sodium Valproate', genericName: 'Valproic Acid', category: 'Anticonvulsant', dosages: ['200mg', '500mg', '1g'], routes: ['Oral', 'IV'], sideEffects: ['Hepatotoxicity', 'Thrombocytopenia', 'Weight gain', 'Tremor', 'Neural tube defects (pregnancy)'], indications: ['Generalized seizures', 'Bipolar disorder', 'Migraine prophylaxis'], contraindications: ['Severe liver disease', 'Pregnancy (avoid if possible)'], nursingConsiderations: ['Monitor LFTs and platelet count', 'Monitor for bruising/bleeding', 'Avoid in pregnancy (fetal risk)'] },
  { name: 'Phenobarbital', genericName: 'Phenobarbital', category: 'Anticonvulsant (Barbiturate)', dosages: ['15mg', '30mg', '60mg', '100mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Sedation', 'Dependence', 'Respiratory depression', 'Rash'], indications: ['Seizures', 'Status epilepticus', 'Neonatal seizures'], contraindications: ['Severe respiratory insufficiency', 'Porphyria'], nursingConsiderations: ['Monitor respiratory function', 'Do not stop abruptly', 'Tolerance and dependence develop'] },
  { name: 'Levetiracetam', genericName: 'Levetiracetam', category: 'Anticonvulsant', dosages: ['250mg', '500mg', '750mg', '1000mg'], routes: ['Oral', 'IV'], sideEffects: ['Dizziness', 'Somnolence', 'Irritability', 'Behavioral changes'], indications: ['Partial seizures', 'Generalized tonic-clonic', 'Status epilepticus'], contraindications: ['Levetiracetam allergy'], nursingConsiderations: ['Monitor for behavioral changes', 'Adjust dose in renal impairment', 'Abrupt withdrawal may increase seizure frequency'] },

  // Antiretrovirals
  { name: 'Tenofovir Disoproxil', genericName: 'Tenofovir DF', category: 'Antiretroviral (NRTI)', dosages: ['300mg'], routes: ['Oral'], sideEffects: ['Renal toxicity', 'Bone loss', 'Nausea', 'Fanconi syndrome'], indications: ['HIV-1 infection', 'HBV infection'], contraindications: ['Renal impairment (CrCl <50)', 'Tenofovir allergy'], nursingConsiderations: ['Monitor renal function and phosphate', 'Monitor bone density with long-term use', 'Take with food'] },
  { name: 'Efavirenz', genericName: 'Efavirenz', category: 'Antiretroviral (NNRTI)', dosages: ['200mg', '600mg'], routes: ['Oral'], sideEffects: ['CNS effects (vivid dreams, dizziness)', 'Rash', 'Hepatotoxicity', 'Hyperlipidemia'], indications: ['HIV-1 infection'], contraindications: ['First trimester pregnancy', 'Severe hepatic impairment'], nursingConsiderations: ['Take on empty stomach at bedtime (reduce CNS effects)', 'Monitor LFTs and cholesterol', 'CNS effects usually resolve in 2-4 weeks'] },
  { name: 'Lamivudine', genericName: 'Lamivudine (3TC)', category: 'Antiretroviral (NRTI)', dosages: ['150mg', '300mg'], routes: ['Oral'], sideEffects: ['Nausea', 'Headache', 'Fatigue', 'Pancreatitis (children)'], indications: ['HIV-1 infection', 'HBV infection'], contraindications: ['Lamivudine allergy'], nursingConsiderations: ['Monitor viral load and CD4 count', 'Can be taken with or without food'] },
  { name: 'Zidovudine', genericName: 'Zidovudine (AZT)', category: 'Antiretroviral (NRTI)', dosages: ['100mg', '200mg', '300mg'], routes: ['Oral', 'IV'], sideEffects: ['Anemia', 'Neutropenia', 'Myopathy', 'Nausea', 'Headache'], indications: ['HIV-1 infection', 'Prevention of maternal-fetal transmission'], contraindications: ['Severe anemia', 'Neutropenia'], nursingConsiderations: ['Monitor CBC closely', 'Monitor for muscle weakness', 'Take with food to reduce GI upset'] },
  { name: 'Nevirapine', genericName: 'Nevirapine', category: 'Antiretroviral (NNRTI)', dosages: ['200mg'], routes: ['Oral'], sideEffects: ['Rash', 'Hepatotoxicity', 'Stevens-Johnson syndrome'], indications: ['HIV-1 infection', 'Prevention of maternal-fetal transmission'], contraindications: ['Severe hepatic impairment', 'Women with CD4 >250', 'Men with CD4 >400'], nursingConsiderations: ['Monitor LFTs frequently', 'Monitor for rash (may progress to SJS)', 'Lead-in dose for first 14 days'] },
  { name: 'Lopinavir/Ritonavir', genericName: 'Lopinavir/Ritonavir', category: 'Antiretroviral (Protease Inhibitor)', dosages: ['100/25mg', '200/50mg'], routes: ['Oral'], sideEffects: ['GI intolerance', 'Hyperlipidemia', 'Hyperglycemia', 'Fat redistribution'], indications: ['HIV-1 infection'], contraindications: ['Severe hepatic impairment'], nursingConsiderations: ['Take with food', 'Monitor lipids and glucose', 'Monitor LFTs'] },
  { name: 'Dolutegravir', genericName: 'Dolutegravir (DTG)', category: 'Antiretroviral (Integrase Inhibitor)', dosages: ['50mg'], routes: ['Oral'], sideEffects: ['Insomnia', 'Headache', 'Weight gain', 'Nausea'], indications: ['HIV-1 infection'], contraindications: ['Dolutegravir allergy'], nursingConsiderations: ['Monitor for insomnia and headache', 'Can be taken without regard to food', 'Preferred first-line ART in many guidelines'] },

  // Anti-TB Drugs
  { name: 'Rifampicin', genericName: 'Rifampin', category: 'Antitubercular', dosages: ['150mg', '300mg', '450mg', '600mg'], routes: ['Oral', 'IV'], sideEffects: ['Hepatotoxicity', 'Red-orange discoloration of bodily fluids', 'Rash', 'Thrombocytopenia'], indications: ['Tuberculosis', 'Leprosy', 'Staphylococcal infections'], contraindications: ['Severe hepatic impairment', 'Porphyria'], nursingConsiderations: ['Warn patient about red-orange urine, tears, sweat', 'Take on empty stomach', 'Monitor LFTs', 'Major CYP450 inducer (many drug interactions)'] },
  { name: 'Isoniazid', genericName: 'Isoniazid (INH)', category: 'Antitubercular', dosages: ['50mg', '100mg', '200mg', '300mg'], routes: ['Oral', 'IM'], sideEffects: ['Peripheral neuropathy', 'Hepatotoxicity', 'Rash', 'Pyridoxine deficiency'], indications: ['Tuberculosis (treatment and prophylaxis)'], contraindications: ['Severe hepatic disease', 'INH allergy'], nursingConsiderations: ['Give pyridoxine (Vitamin B6) to prevent neuropathy', 'Monitor LFTs', 'Avoid alcohol', 'Take on empty stomach'] },
  { name: 'Pyrazinamide', genericName: 'Pyrazinamide (PZA)', category: 'Antitubercular', dosages: ['400mg', '500mg', '750mg', '1g'], routes: ['Oral'], sideEffects: ['Hepatotoxicity', 'Hyperuricemia', 'Arthralgia', 'Rash'], indications: ['Tuberculosis'], contraindications: ['Severe hepatic damage', 'Acute gout'], nursingConsiderations: ['Monitor LFTs and uric acid', 'Report joint pain', 'Take with food to reduce GI upset'] },
  { name: 'Ethambutol', genericName: 'Ethambutol (EMB)', category: 'Antitubercular', dosages: ['100mg', '200mg', '400mg', '800mg'], routes: ['Oral'], sideEffects: ['Optic neuritis (decreased visual acuity)', 'Rash', 'Hyperuricemia'], indications: ['Tuberculosis'], contraindications: ['Optic neuritis', 'Children <6 years (difficult to monitor vision)'], nursingConsiderations: ['Test visual acuity before and during treatment', 'Monitor for red-green color blindness', 'Report any visual changes immediately'] },
  { name: 'Streptomycin', genericName: 'Streptomycin', category: 'Antitubercular (Aminoglycoside)', dosages: ['500mg', '750mg', '1g'], routes: ['IM'], sideEffects: ['Ototoxicity', 'Nephrotoxicity', 'Neuromuscular blockade'], indications: ['Tuberculosis', 'Plague', 'Brucellosis'], contraindications: ['Pregnancy', 'Myasthenia gravis', 'Renal impairment'], nursingConsiderations: ['Monitor renal function', 'Monitor hearing', 'Given IM only (never IV)', 'Rotate injection sites'] },

  // Emergency/Critical Care
  { name: 'Adrenaline', genericName: 'Epinephrine', category: 'Emergency/Cardiac', dosages: ['1mg/ml (1:1000)', '0.1mg/ml (1:10000)'], routes: ['IV', 'IM', 'SC', 'Endotracheal'], sideEffects: ['Hypertension', 'Tachycardia', 'Arrhythmias', 'Anxiety', 'Hyperglycemia'], indications: ['Anaphylaxis', 'Cardiac arrest', 'Severe asthma'], contraindications: ['Hypertension (relative)', 'Arrhythmias (relative)'], nursingConsiderations: ['1:1000 for IM anaphylaxis (0.3-0.5mg)', '1:10,000 for IV cardiac arrest (1mg q3-5min)', 'Monitor ECG and BP', 'Check concentration carefully before use'] },
  { name: 'Atropine', genericName: 'Atropine Sulfate', category: 'Emergency/Cardiac', dosages: ['0.3mg', '0.4mg', '0.5mg', '0.6mg', '1mg'], routes: ['IV', 'IM', 'SC'], sideEffects: ['Dry mouth', 'Blurred vision', 'Tachycardia', 'Urinary retention', 'Constipation'], indications: ['Bradycardia', 'Organophosphate poisoning', 'Pre-anesthetic'], contraindications: ['Narrow-angle glaucoma', 'Myasthenia gravis', 'Obstructive GI disorders'], nursingConsiderations: ['Monitor HR after administration', 'Dose 0.5mg q3-5min for bradycardia (max 3mg)', 'Antidote: physostigmine'] },
  { name: 'Lidocaine', genericName: 'Lidocaine HCl', category: 'Antiarrhythmic/Local Anesthetic', dosages: ['1%', '2%', '5%'], routes: ['IV', 'SC', 'Topical', 'Intranasal'], sideEffects: ['CNS depression', 'Seizures', 'Hypotension', 'Methemoglobinemia'], indications: ['Ventricular arrhythmias', 'Local anesthesia'], contraindications: ['Severe heart block', 'Adams-Stokes syndrome'], nursingConsiderations: ['Monitor ECG continuously', 'Reduce dose in liver disease', 'Check for signs of toxicity (perioral numbness, metallic taste)'] },
  { name: 'Amiodarone', genericName: 'Amiodarone', category: 'Antiarrhythmic', dosages: ['200mg', '400mg', '600mg (loading)'], routes: ['Oral', 'IV'], sideEffects: ['Pulmonary fibrosis', 'Thyroid dysfunction', 'Corneal deposits', 'Photosensitivity', 'Hepatotoxicity'], indications: ['Ventricular arrhythmias', 'Atrial fibrillation'], contraindications: ['Severe sinus bradycardia', 'Thyroid disease'], nursingConsiderations: ['Monitor pulmonary function', 'Monitor thyroid and LFTs', 'Use sun protection', 'Monitor for corneal deposits'] },
  { name: 'Adenosine', genericName: 'Adenosine', category: 'Antiarrhythmic', dosages: ['6mg', '12mg', '18mg'], routes: ['IV (rapid bolus)'], sideEffects: ['Facial flushing', 'Chest pain', 'Bronchospasm', 'Bradycardia', 'Transient asystole'], indications: ['Paroxysmal SVT', 'Diagnostic aid'], contraindications: ['Second/third-degree AV block', 'Asthma', 'Sick sinus syndrome'], nursingConsiderations: ['Give as rapid IV bolus (1-2 sec) followed by flush', 'Monitor ECG continuously', 'Warn patient about transient flushing and palpitations'] },
  { name: 'Sodium Bicarbonate', genericName: 'Sodium Bicarbonate', category: 'Emergency', dosages: ['8.4% (1mEq/ml)', '4.2% (0.5mEq/ml)'], routes: ['IV'], sideEffects: ['Metabolic alkalosis', 'Hypernatremia', 'Hypokalemia', 'Tissue necrosis (extravasation)'], indications: ['Metabolic acidosis', 'Hyperkalemia', 'TCA overdose'], contraindications: ['Metabolic alkalosis', 'Hypocalcemia'], nursingConsiderations: ['Do not mix with calcium solutions', 'Monitor ABG and electrolytes', 'Check for extravasation'] },
  { name: 'Calcium Gluconate', genericName: 'Calcium Gluconate', category: 'Emergency', dosages: ['10% (1g/10ml)'], routes: ['IV'], sideEffects: ['Bradycardia', 'Tissue necrosis (extravasation)', 'Hypercalcemia'], indications: ['Hypocalcemia', 'Hyperkalemia', 'Magnesium toxicity', 'Calcium channel blocker overdose'], contraindications: ['Hypercalcemia', 'Ventricular fibrillation'], nursingConsiderations: ['Administer slowly via central line if possible', 'Monitor ECG', 'Do not mix with bicarbonate or phosphate'] },
  { name: 'Magnesium Sulfate', genericName: 'Magnesium Sulfate', category: 'Emergency/Electrolyte', dosages: ['1g', '2g', '4g', '5g'], routes: ['IV', 'IM'], sideEffects: ['Flushing', 'Hypotension', 'Respiratory depression', 'Loss of reflexes'], indications: ['Eclampsia', 'Hypomagnesemia', 'Torsades de pointes', 'Severe asthma'], contraindications: ['Heart block', 'Renal failure', 'Myasthenia gravis'], nursingConsiderations: ['Monitor reflexes, RR, and BP before each dose', 'Calcium gluconate is antidote', 'Monitor magnesium levels'] },
  { name: 'Naloxone', genericName: 'Naloxone HCl', category: 'Emergency (Opioid Antagonist)', dosages: ['0.4mg', '2mg', '4mg'], routes: ['IV', 'IM', 'SC', 'Intranasal'], sideEffects: ['Acute withdrawal', 'Hypertension', 'Tachycardia', 'Pulmonary edema'], indications: ['Opioid overdose', 'Respiratory depression from opioids'], contraindications: ['Opioid dependence (precipitates withdrawal)'], nursingConsiderations: ['May need repeated doses (shorter than most opioids)', 'Monitor respiratory status closely', 'Can cause acute withdrawal symptoms'] },
  { name: 'Flumazenil', genericName: 'Flumazenil', category: 'Emergency (Benzodiazepine Antagonist)', dosages: ['0.2mg', '0.3mg', '0.5mg'], routes: ['IV'], sideEffects: ['Panic attacks', 'Seizures (in dependent patients)', 'Dizziness'], indications: ['Benzodiazepine overdose', 'Reversal of conscious sedation'], contraindications: ['Mixed overdose with TCA', 'Benzodiazepine dependence (risk of seizures)'], nursingConsiderations: ['Monitor for resedation', 'Administer slowly', 'Use caution in chronic benzodiazepine users'] },

  // Respiratory
  { name: 'Salbutamol', genericName: 'Albuterol', category: 'Bronchodilator (Beta-2 Agonist)', dosages: ['100mcg', '200mcg', '2mg', '4mg', '5mg/ml (nebulizer)'], routes: ['Inhalation', 'Oral', 'IV', 'Nebulized'], sideEffects: ['Tremor', 'Tachycardia', 'Palpitations', 'Headache', 'Hypokalemia'], indications: ['Asthma', 'COPD', 'Bronchospasm'], contraindications: ['Tachyarrhythmias'], nursingConsiderations: ['Monitor HR after administration', 'Teach proper inhaler technique', 'Rinse mouth after inhaled use'] },
  { name: 'Ipratropium Bromide', genericName: 'Ipratropium', category: 'Bronchodilator (Anticholinergic)', dosages: ['20mcg', '40mcg', '0.5mg/2.5ml (nebulizer)'], routes: ['Inhalation', 'Nebulized'], sideEffects: ['Dry mouth', 'Cough', 'Headache', 'Blurred vision'], indications: ['COPD', 'Asthma', 'Rhinorrhea'], contraindications: ['Atropine allergy'], nursingConsiderations: ['Do not use for acute episodes alone (combine with salbutamol)', 'Avoid contact with eyes'] },
  { name: 'Aminophylline', genericName: 'Aminophylline', category: 'Bronchodilator (Xanthine)', dosages: ['100mg', '200mg', '250mg', '500mg'], routes: ['Oral', 'IV'], sideEffects: ['Nausea', 'Tachycardia', 'Seizures (toxicity)', 'Insomnia'], indications: ['COPD', 'Asthma', 'Neonatal apnea'], contraindications: ['Seizure disorder', 'Active peptic ulcer', 'Tachyarrhythmias'], nursingConsiderations: ['Monitor theophylline levels (10-20 mcg/mL)', 'Monitor HR', 'Many drug interactions'] },

  // GI Drugs
  { name: 'Omeprazole', genericName: 'Omeprazole', category: 'PPI', dosages: ['10mg', '20mg', '40mg'], routes: ['Oral', 'IV'], sideEffects: ['Headache', 'Nausea', 'Vitamin B12 deficiency (long-term)', 'Hypomagnesemia'], indications: ['GERD', 'Peptic ulcer', 'Zollinger-Ellison syndrome', 'Stress ulcer prophylaxis'], contraindications: ['Long-term use without need'], nursingConsiderations: ['Take before breakfast', 'Do not crush capsules (may open and sprinkle)', 'Monitor Mg levels with prolonged use'] },
  { name: 'Ranitidine', genericName: 'Ranitidine', category: 'H2 Antagonist', dosages: ['150mg', '300mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Headache', 'Dizziness', 'Confusion (elderly)', 'Thrombocytopenia (rare)'], indications: ['GERD', 'Peptic ulcer', 'Zollinger-Ellison syndrome'], contraindications: ['Porphyria'], nursingConsiderations: ['Take with or without food', 'Monitor for confusion in elderly', 'May interfere with warfarin and theophylline'] },
  { name: 'Ondansetron', genericName: 'Ondansetron', category: 'Antiemetic (5-HT3 Antagonist)', dosages: ['4mg', '8mg', '24mg'], routes: ['Oral', 'IV', 'IM', 'ODT'], sideEffects: ['Headache', 'Constipation', 'QT prolongation', 'Fatigue'], indications: ['Nausea and vomiting', 'Post-operative N/V', 'Chemotherapy-induced N/V'], contraindications: ['Congenital QT prolongation'], nursingConsiderations: ['Monitor ECG with high doses', 'Can mask intestinal obstruction', 'Most effective as prophylaxis'] },
  { name: 'Metoclopramide', genericName: 'Metoclopramide', category: 'Antiemetic/Prokinetic', dosages: ['5mg', '10mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Extrapyramidal symptoms', 'Drowsiness', 'Galactorrhea', 'Tardive dyskinesia (long-term)'], indications: ['Nausea and vomiting', 'Gastroparesis', 'GERD'], contraindications: ['GI obstruction', 'Parkinson disease', 'Seizure disorder'], nursingConsiderations: ['Monitor for EPS (especially in young and elderly)', 'Do not use >12 weeks (tardive dyskinesia)', 'Give 30 min before meals'] },
  { name: 'Loperamide', genericName: 'Loperamide', category: 'Antidiarrheal', dosages: ['2mg', '4mg'], routes: ['Oral'], sideEffects: ['Constipation', 'Dizziness', 'Dry mouth'], indications: ['Diarrhea', 'Traveler diarrhea'], contraindications: ['Active colitis', 'Dysentery (bloody stool)', 'Children <2 years'], nursingConsiderations: ['Do not use if fever or bloody stools', 'Discontinue if no improvement in 48h', 'Monitor for constipation'] },
  { name: 'Bisacodyl', genericName: 'Bisacodyl', category: 'Laxative (Stimulant)', dosages: ['5mg', '10mg'], routes: ['Oral', 'PR'], sideEffects: ['Abdominal cramps', 'Diarrhea', 'Electrolyte imbalance'], indications: ['Constipation', 'Bowel preparation'], contraindications: ['Intestinal obstruction', 'Acute abdomen'], nursingConsiderations: ['Do not crush enteric-coated tablets', 'Take at bedtime for morning effect', 'Do not use within 1 hour of antacids or milk'] },
  { name: 'Lactulose', genericName: 'Lactulose', category: 'Laxative (Osmotic)/Ammonia Reducer', dosages: ['10g/15ml', '20g/30ml'], routes: ['Oral'], sideEffects: ['Flatulence', 'Abdominal cramps', 'Diarrhea', 'Electrolyte imbalance'], indications: ['Constipation', 'Hepatic encephalopathy'], contraindications: ['Galactosemia', 'Intestinal obstruction'], nursingConsiderations: ['Monitor stool output', 'For constipation: titrate to produce soft stool', 'For encephalopathy: 2-3 soft stools/day'] },

  // Endocrine/Hormonal
  { name: 'Metformin', genericName: 'Metformin HCl', category: 'Antidiabetic (Biguanide)', dosages: ['500mg', '850mg', '1000mg'], routes: ['Oral'], sideEffects: ['GI upset', 'Metallic taste', 'Lactic acidosis (rare)', 'Vitamin B12 deficiency'], indications: ['Type 2 diabetes mellitus', 'PCOS'], contraindications: ['Renal impairment (eGFR <30)', 'Hepatic disease', 'Alcoholism', 'Acute HF'], nursingConsiderations: ['Take with meals to reduce GI upset', 'Monitor renal function', 'Hold before contrast studies', 'Monitor for lactic acidosis (rare but serious)'] },
  { name: 'Glibenclamide', genericName: 'Glyburide', category: 'Antidiabetic (Sulfonylurea)', dosages: ['2.5mg', '5mg', '10mg'], routes: ['Oral'], sideEffects: ['Hypoglycemia', 'Weight gain', 'GI upset'], indications: ['Type 2 diabetes mellitus'], contraindications: ['Type 1 diabetes', 'Severe renal/hepatic impairment'], nursingConsiderations: ['Take 30 min before meals', 'Monitor blood glucose', 'Warn about hypoglycemia symptoms'] },
  { name: 'Insulin (Regular)', genericName: 'Soluble Insulin', category: 'Antidiabetic (Rapid-acting)', dosages: ['Variable'], routes: ['SC', 'IV'], sideEffects: ['Hypoglycemia', 'Weight gain', 'Lipodystrophy at injection site'], indications: ['Diabetes mellitus (all types)', 'Hyperkalemia', 'DKA'], contraindications: ['Hypoglycemia'], nursingConsiderations: ['Rotate injection sites', 'Do not mix with other insulins unless specified', 'Monitor blood glucose', 'Short-acting: onset 30 min, peak 2-4h, duration 6-8h'] },
  { name: 'Insulin (NPH)', genericName: 'Isophane Insulin', category: 'Antidiabetic (Intermediate-acting)', dosages: ['Variable'], routes: ['SC'], sideEffects: ['Hypoglycemia', 'Weight gain', 'Lipodystrophy'], indications: ['Diabetes mellitus'], contraindications: ['Hypoglycemia'], nursingConsiderations: ['Rotate injection sites', 'Milky/cloudy appearance (must be resuspended)', 'Onset 2-4h, peak 4-10h, duration 12-18h'] },
  { name: 'Dexamethasone', genericName: 'Dexamethasone', category: 'Corticosteroid', dosages: ['0.5mg', '0.75mg', '1.5mg', '4mg', '8mg', '16mg'], routes: ['Oral', 'IV', 'IM', 'Topical', 'Ophthalmic'], sideEffects: ['Hyperglycemia', 'Weight gain', 'Osteoporosis', 'Immunosuppression', 'Adrenal suppression'], indications: ['Inflammation', 'Cerebral edema', 'COVID-19', 'Allergic reactions', 'Chemotherapy adjunct'], contraindications: ['Systemic fungal infections', 'Live vaccines'], nursingConsiderations: ['Taper dose gradually (do not stop abruptly)', 'Monitor blood glucose', 'Give with food to reduce GI upset', 'Monitor for signs of infection'] },
  { name: 'Prednisolone', genericName: 'Prednisolone', category: 'Corticosteroid', dosages: ['5mg', '10mg', '15mg', '20mg', '30mg', '40mg', '50mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Hyperglycemia', 'Osteoporosis', 'Weight gain', 'Immunosuppression', 'Cushing syndrome'], indications: ['Asthma', 'Rheumatoid arthritis', 'Allergic disorders', 'Autoimmune diseases'], contraindications: ['Systemic fungal infections'], nursingConsiderations: ['Give with food or milk', 'Taper dose gradually', 'Monitor glucose and BP'] },
  { name: 'Hydrocortisone', genericName: 'Hydrocortisone', category: 'Corticosteroid', dosages: ['10mg', '20mg', '50mg', '100mg'], routes: ['Oral', 'IV', 'IM', 'Topical', 'PR'], sideEffects: ['Hyperglycemia', 'Fluid retention', 'Hypertension', 'Immunosuppression'], indications: ['Adrenal insufficiency', 'Inflammation', 'Allergic reactions', 'Septic shock'], contraindications: ['Systemic fungal infections'], nursingConsiderations: ['Monitor glucose and BP', 'Stress dose needed during illness/surgery', 'Taper gradually'] },
  { name: 'Levothyroxine', genericName: 'Levothyroxine Sodium (T4)', category: 'Thyroid Hormone', dosages: ['25mcg', '50mcg', '75mcg', '100mcg', '125mcg', '150mcg', '200mcg'], routes: ['Oral', 'IV'], sideEffects: ['Tachycardia', 'Palpitations', 'Weight loss', 'Insomnia', 'Heat intolerance'], indications: ['Hypothyroidism', 'Myxedema coma'], contraindications: ['Thyrotoxicosis', 'Acute MI'], nursingConsiderations: ['Take on empty stomach 30-60 min before breakfast', 'Do not take with calcium/iron supplements', 'Monitor TSH levels', 'Consistent brand recommended'] },
  { name: 'Carbimazole', genericName: 'Carbimazole', category: 'Antithyroid', dosages: ['5mg', '10mg', '20mg'], routes: ['Oral'], sideEffects: ['Agranulocytosis', 'Rash', 'Nausea', 'Joint pain'], indications: ['Hyperthyroidism', 'Thyroid storm'], contraindications: ['Severe agranulocytosis'], nursingConsiderations: ['Monitor CBC (especially neutrophils)', 'Report sore throat/fever immediately', 'Take with food'] },

  // OB/GYN
  { name: 'Oxytocin', genericName: 'Oxytocin', category: 'Uterotonic', dosages: ['5IU', '10IU'], routes: ['IV', 'IM'], sideEffects: ['Nausea', 'Hypotension', 'Water intoxication', 'Uterine hyperstimulation'], indications: ['Induction of labor', 'Augmentation of labor', 'Postpartum hemorrhage'], contraindications: ['Fetal distress', 'Cephalopelvic disproportion', 'Uterine scarring'], nursingConsiderations: ['Monitor uterine contractions and FHR continuously', 'Do not give as IV push for PPH', 'Monitor I/O (antidiuretic effect)'] },
  { name: 'Misoprostol', genericName: 'Misoprostol', category: 'Prostaglandin', dosages: ['25mcg', '50mcg', '100mcg', '200mcg'], routes: ['Oral', 'Sublingual', 'Vaginal', 'PR'], sideEffects: ['Diarrhea', 'Uterine cramps', 'Nausea', 'Fever'], indications: ['Postpartum hemorrhage', 'Induction of labor', 'Medical abortion', 'GI ulcer prevention (with NSAIDs)'], contraindications: ['Pregnancy (for GI use)', 'Uterine scarring'], nursingConsiderations: ['Monitor vaginal bleeding', 'Monitor uterine tone', 'Can cause shivering and fever'] },
  { name: 'Ergometrine', genericName: 'Ergonovine', category: 'Uterotonic', dosages: ['0.2mg', '0.5mg'], routes: ['IV', 'IM'], sideEffects: ['Nausea', 'Hypertension', 'Headache', 'Coronary vasospasm'], indications: ['Postpartum hemorrhage', 'Uterine atony'], contraindications: ['Hypertension', 'Pre-eclampsia', 'Peripheral vascular disease'], nursingConsiderations: ['Monitor BP closely', 'Do not use in hypertensive patients', 'Monitor vaginal bleeding'] },
  { name: 'Magnesium Sulfate (OB)', genericName: 'Magnesium Sulfate', category: 'Anticonvulsant (OB)', dosages: ['4g loading', '1-2g/hour maintenance'], routes: ['IV', 'IM'], sideEffects: ['Flushing', 'Respiratory depression', 'Loss of deep tendon reflexes', 'Hypotension'], indications: ['Pre-eclampsia', 'Eclampsia'], contraindications: ['Myasthenia gravis', 'Heart block', 'Renal failure'], nursingConsiderations: ['Monitor DTRs, RR, and urine output hourly', 'Calcium gluconate is antidote', 'Monitor Mg levels (therapeutic 4-7 mEq/L)'] },

  // Hematinics/Vitamins
  { name: 'Ferrous Sulfate', genericName: 'Iron (FeSO4)', category: 'Hematinic', dosages: ['200mg (65mg elemental iron)', '300mg (95mg elemental)'], routes: ['Oral', 'IV (Iron sucrose)'], sideEffects: ['GI upset', 'Constipation', 'Dark stools', 'Nausea'], indications: ['Iron deficiency anemia', 'Pregnancy prophylaxis'], contraindications: ['Hemochromatosis', 'Hemolytic anemia', 'Thalassemia (not iron deficient)'], nursingConsiderations: ['Take with vitamin C for absorption', 'Avoid tea, coffee, and milk within 1 hour', 'Do not crush SR tablets', 'Stools will turn dark green/black'] },
  { name: 'Folic Acid', genericName: 'Folic Acid', category: 'Vitamin B9', dosages: ['400mcg', '5mg'], routes: ['Oral', 'IM', 'IV'], sideEffects: ['Rare (generally well tolerated)'], indications: ['Megaloblastic anemia', 'Pregnancy (neural tube defect prevention)', 'Methotrexate adjunct'], contraindications: ['Untreated vitamin B12 deficiency (may mask)'], nursingConsiderations: ['Give with B12 for megaloblastic anemia', 'Check B12 levels before treatment', 'Recommend 400mcg daily for all pregnant women'] },
  { name: 'Vitamin B12', genericName: 'Cyanocobalamin', category: 'Vitamin B12', dosages: ['100mcg', '1000mcg'], routes: ['Oral', 'IM', 'SC'], sideEffects: ['Hypokalemia (during initial treatment)', 'Diarrhea', 'Rash'], indications: ['Pernicious anemia', 'Vitamin B12 deficiency', 'Megaloblastic anemia'], contraindications: ['Cyanocobalamin allergy'], nursingConsiderations: ['Monitor potassium during initial therapy', 'IM injections are painful', 'Lifelong therapy for pernicious anemia'] },
  { name: 'Vitamin C', genericName: 'Ascorbic Acid', category: 'Vitamin', dosages: ['100mg', '250mg', '500mg', '1000mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Diarrhea (high dose)', 'GI upset', 'Kidney stones (high dose)'], indications: ['Vitamin C deficiency (scurvy)', 'Wound healing', 'Immunity'], contraindications: ['Kidney stones', 'G6PD deficiency (high dose IV)'], nursingConsiderations: ['Do not exceed 2g daily without monitoring', 'Enhances iron absorption', 'High doses may interfere with glucose tests'] },
  { name: 'Vitamin D', genericName: 'Cholecalciferol (D3)', category: 'Vitamin', dosages: ['400IU', '800IU', '1000IU', '2000IU', '50000IU'], routes: ['Oral', 'IM'], sideEffects: ['Hypercalcemia', 'Nausea', 'Weakness (high dose)'], indications: ['Vitamin D deficiency', 'Osteoporosis', 'Rickets'], contraindications: ['Hypercalcemia', 'Hypervitaminosis D'], nursingConsiderations: ['Monitor calcium with high-dose therapy', 'Sunlight is also a source', 'Given with calcium for osteoporosis'] },
  { name: 'Vitamin K', genericName: 'Phytomenadione (K1)', category: 'Vitamin', dosages: ['1mg', '5mg', '10mg'], routes: ['Oral', 'IV', 'IM', 'SC'], sideEffects: ['Hypotension (rapid IV)', 'Flushing', 'Rare anaphylaxis'], indications: ['Warfarin reversal', 'Neonatal prophylaxis', 'Vitamin K deficiency'], contraindications: ['Severe hepatic disease (may not work)'], nursingConsiderations: ['Administer IV slowly (max 1mg/min)', 'IM for neonates (routine prophylaxis)', 'Antidote for warfarin'] },

  // Psychiatric
  { name: 'Fluoxetine', genericName: 'Fluoxetine', category: 'SSRI Antidepressant', dosages: ['20mg', '40mg', '60mg'], routes: ['Oral'], sideEffects: ['Nausea', 'Insomnia', 'Sexual dysfunction', 'Serotonin syndrome'], indications: ['Major depressive disorder', 'OCD', 'Bulimia', 'Panic disorder'], contraindications: ['MAOI use', 'Bipolar (may cause mania)'], nursingConsiderations: ['Take in the morning (may cause insomnia)', 'Monitor for suicidal ideation (first weeks)', 'Long half-life (4-6 days)', 'Serotonin syndrome risk with other serotonergic drugs'] },
  { name: 'Sertraline', genericName: 'Sertraline', category: 'SSRI Antidepressant', dosages: ['25mg', '50mg', '100mg', '200mg'], routes: ['Oral'], sideEffects: ['Nausea', 'Diarrhea', 'Insomnia', 'Sexual dysfunction'], indications: ['Depression', 'PTSD', 'Panic disorder', 'OCD', 'PMDD'], contraindications: ['MAOI use', 'Bipolar'], nursingConsiderations: ['Take with food to reduce GI upset', 'Monitor weight changes', 'Most common SSRI for breastfeeding'] },
  { name: 'Haloperidol', genericName: 'Haloperidol', category: 'Antipsychotic (Typical)', dosages: ['0.5mg', '1mg', '2mg', '5mg', '10mg'], routes: ['Oral', 'IM', 'IV'], sideEffects: ['EPS (dystonia, akathisia)', 'Tardive dyskinesia', 'QT prolongation', 'Neuroleptic malignant syndrome'], indications: ['Schizophrenia', 'Acute psychosis', 'Delirium', 'Tourette syndrome'], contraindications: ['Parkinson disease', 'QT prolongation'], nursingConsiderations: ['Monitor for EPS and NMS', 'Monitor ECG', 'Give with anticholinergic if EPS develops', 'Avoid with grapefruit juice'] },
  { name: 'Risperidone', genericName: 'Risperidone', category: 'Antipsychotic (Atypical)', dosages: ['0.5mg', '1mg', '2mg', '3mg', '4mg', '6mg'], routes: ['Oral', 'IM (depot)'], sideEffects: ['Weight gain', 'Hyperprolactinemia', 'Sedation', 'EPS (dose-dependent)'], indications: ['Schizophrenia', 'Bipolar disorder', 'Autism (irritability)'], contraindications: ['Risperidone allergy'], nursingConsiderations: ['Monitor weight and metabolic parameters', 'Monitor prolactin', 'Lower starting dose in elderly', 'Monitor for suicidal ideation'] },
  { name: 'Diazepam (Psych)', genericName: 'Diazepam', category: 'Anxiolytic/Benzodiazepine', dosages: ['2mg', '5mg', '10mg'], routes: ['Oral', 'IV', 'PR'], sideEffects: ['Sedation', 'Dependence', 'Respiratory depression', 'Paradoxical excitement'], indications: ['Anxiety', 'Panic disorder', 'Alcohol withdrawal', 'Muscle spasm'], contraindications: ['Severe respiratory insufficiency', 'Myasthenia gravis'], nursingConsiderations: ['Short-term use only (dependency risk)', 'Do not stop abruptly', 'Avoid alcohol', 'Avoid driving'] },

  // Antihistamines
  { name: 'Chlorpheniramine', genericName: 'Chlorphenamine', category: 'Antihistamine (First-gen)', dosages: ['4mg', '8mg', '12mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Sedation', 'Dizziness', 'Dry mouth', 'Urinary retention'], indications: ['Allergic reactions', 'Hay fever', 'Urticaria', 'Common cold'], contraindications: ['Narrow-angle glaucoma', 'BPH', 'Asthma (acute)'], nursingConsiderations: ['May cause drowsiness (avoid driving)', 'Caution in elderly', 'Monitor for anticholinergic effects'] },
  { name: 'Loratadine', genericName: 'Loratadine', category: 'Antihistamine (Second-gen)', dosages: ['10mg'], routes: ['Oral'], sideEffects: ['Headache', 'Dry mouth', 'Fatigue (less sedation)'], indications: ['Allergic rhinitis', 'Urticaria'], contraindications: ['Loratadine allergy'], nursingConsiderations: ['Non-sedating (preferred for daytime)', 'Can be taken with or without food'] },
  { name: 'Cetirizine', genericName: 'Cetirizine', category: 'Antihistamine (Second-gen)', dosages: ['10mg'], routes: ['Oral'], sideEffects: ['Mild sedation', 'Dry mouth', 'Headache'], indications: ['Allergic rhinitis', 'Urticaria', 'Pruritus'], contraindications: ['Cetirizine allergy'], nursingConsiderations: ['Some sedation may occur (caution with driving)', 'Reduce dose in renal impairment'] },

  // Fluids & Electrolytes
  { name: 'Normal Saline', genericName: '0.9% Sodium Chloride', category: 'IV Fluid (Crystalloid)', dosages: ['100ml', '250ml', '500ml', '1000ml'], routes: ['IV'], sideEffects: ['Hypernatremia (excessive)', 'Fluid overload', 'Dilutional acidosis'], indications: ['Hypovolemia', 'Dehydration', 'Resuscitation', 'Fluid maintenance'], contraindications: ['Severe hypernatremia', 'Heart failure (caution)'], nursingConsiderations: ['Monitor I/O', 'Check for signs of fluid overload', 'Do not use with blood in same line (hemolysis)'] },
  { name: 'Ringer Lactate', genericName: 'Hartmann Solution', category: 'IV Fluid (Baltered Crystalloid)', dosages: ['500ml', '1000ml'], routes: ['IV'], sideEffects: ['Hyponatremia (excessive)', 'Fluid overload', 'Metabolic alkalosis'], indications: ['Resuscitation', 'Burn management', 'Metabolic acidosis'], contraindications: ['Lactic acidosis', 'Severe liver disease (poor lactate metabolism)'], nursingConsiderations: ['Monitor I/O and electrolytes', 'Not compatible with blood in same line'] },
  { name: 'Dextrose 5%', genericName: 'D5W', category: 'IV Fluid', dosages: ['100ml', '250ml', '500ml', '1000ml'], routes: ['IV'], sideEffects: ['Hyperglycemia', 'Dilutional hyponatremia', 'Fluid overload'], indications: ['Fluid maintenance', 'Hypoglycemia', 'Hypernatremia'], contraindications: ['Hyperglycemia', 'Head injury (may worsen cerebral edema)'], nursingConsiderations: ['Monitor blood glucose', 'Do not give with blood (hemolysis)', 'Monitor I/O'] },

  // Pediatric
  { name: 'Vitamin K (Neonatal)', genericName: 'Phytomenadione', category: 'Neonatal Prophylaxis', dosages: ['1mg (IM)', '2mg (Oral)'], routes: ['IM', 'Oral'], sideEffects: ['Pain at injection site', 'Rare anaphylaxis'], indications: ['Hemorrhagic disease of newborn prophylaxis'], contraindications: ['None routine'], nursingConsiderations: ['Given to all neonates at birth', 'IM preferred (more reliable absorption)', 'Document administration'] },
  { name: 'Paracetamol (Pediatric)', genericName: 'Acetaminophen', category: 'Analgesic/Antipyretic (Pediatric)', dosages: ['10-15mg/kg/dose'], routes: ['Oral', 'PR'], sideEffects: ['Liver toxicity (overdose)', 'Rash (rare)'], indications: ['Fever', 'Mild to moderate pain'], contraindications: ['Severe liver disease'], nursingConsiderations: ['Weight-based dosing (10-15 mg/kg q4-6h)', 'Max 60mg/kg/day', 'Avoid in severe liver impairment'] },
  { name: 'Ibuprofen (Pediatric)', genericName: 'Ibuprofen', category: 'NSAID (Pediatric)', dosages: ['5-10mg/kg/dose'], routes: ['Oral'], sideEffects: ['GI upset', 'Renal impairment (dehydration)'], indications: ['Fever', 'Pain', 'Juvenile arthritis'], contraindications: ['Dehydration', 'Asthma (sensitive)', 'GI bleeding'], nursingConsiderations: ['Weight-based dosing (5-10 mg/kg q6-8h)', 'Avoid in dehydrated children', 'Give with food'] },
  { name: 'ORS', genericName: 'Oral Rehydration Salts', category: 'Rehydration', dosages: ['20.5g/L (WHO formula)'], routes: ['Oral'], sideEffects: ['Hypernatremia (if mixed incorrectly)', 'Vomiting (if given too fast)'], indications: ['Dehydration from diarrhea', 'Vomiting'], contraindications: ['Severe dehydration (IV needed first)', 'Ileus'], nursingConsiderations: ['Mix with correct amount of clean water', 'Give small frequent sips', 'Continue breastfeeding', 'Monitor stool output'] },

  // Antifungals
  { name: 'Fluconazole', genericName: 'Fluconazole', category: 'Antifungal (Azole)', dosages: ['50mg', '100mg', '150mg', '200mg'], routes: ['Oral', 'IV'], sideEffects: ['Nausea', 'Headache', 'Hepatotoxicity', 'QT prolongation'], indications: ['Candidiasis', 'Cryptococcal meningitis', 'Dermatophyte infections'], contraindications: ['Azole allergy', 'Prolonged QT interval'], nursingConsiderations: ['Monitor LFTs', 'Take with or without food', '150mg single dose for vaginal candidiasis'] },
  { name: 'Clotrimazole', genericName: 'Clotrimazole', category: 'Antifungal (Azole)', dosages: ['1% cream', '100mg vaginal tablet', '500mg vaginal tablet'], routes: ['Topical', 'Vaginal', 'Oral (lozenge)'], sideEffects: ['Local irritation', 'Rash', 'Burning sensation'], indications: ['Vaginal candidiasis', 'Dermatophytosis', 'Oral thrush'], contraindications: ['Clotrimazole allergy'], nursingConsiderations: ['Wash hands before and after application', 'Complete full course even if symptoms resolve'] },
  { name: 'Nystatin', genericName: 'Nystatin', category: 'Antifungal (Polyene)', dosages: ['100,000U', '500,000U', '1,000,000U'], routes: ['Oral (suspension/tablets)', 'Topical', 'Vaginal'], sideEffects: ['Nausea', 'Diarrhea (oral)', 'Local irritation'], indications: ['Oral thrush', 'Cutaneous candidiasis', 'Vaginal candidiasis'], contraindications: ['Nystatin allergy'], nursingConsiderations: ['Swish and swallow for oral thrush', 'Hold suspension in mouth for 30 sec', 'Continue for 48h after symptoms resolve'] },

  // Antivirals
  { name: 'Acyclovir', genericName: 'Acyclovir', category: 'Antiviral', dosages: ['200mg', '400mg', '800mg'], routes: ['Oral', 'IV', 'Topical'], sideEffects: ['Nausea', 'Headache', 'Renal impairment (IV)', 'Confusion'], indications: ['HSV infections', 'Varicella zoster', 'Herpes zoster'], contraindications: ['Acyclovir allergy'], nursingConsiderations: ['Hydrate well with IV administration', 'Monitor renal function', 'Start at earliest sign of outbreak'] },
  { name: 'Oseltamivir', genericName: 'Oseltamivir (Tamiflu)', category: 'Antiviral (Neuraminidase Inhibitor)', dosages: ['30mg', '45mg', '75mg'], routes: ['Oral'], sideEffects: ['Nausea', 'Vomiting', 'Headache', 'Delirium (rare)'], indications: ['Influenza A & B treatment and prophylaxis'], contraindications: ['Oseltamivir allergy'], nursingConsiderations: ['Start within 48 hours of symptom onset', 'Take with food to reduce GI upset', 'May not be effective in severe illness'] },

  // Anesthetics
  { name: 'Ketamine', genericName: 'Ketamine HCl', category: 'Anesthetic (Dissociative)', dosages: ['0.5mg/kg (analgesic)', '1-2mg/kg (induction)'], routes: ['IV', 'IM', 'Intranasal', 'Oral'], sideEffects: ['Hallucinations', 'Hypertension', 'Increased ICP', 'Laryngospasm', 'Emergence delirium'], indications: ['Induction of anesthesia', 'Procedural sedation', 'Pain management', 'Status epilepticus'], contraindications: ['Hypertension (severe)', 'Increased ICP', 'Schizophrenia'], nursingConsiderations: ['Use in controlled environment (emergency setting)', 'Monitor airway', 'May co-administer with benzodiazepine to reduce emergence reactions'] },
  { name: 'Thiopental Sodium', genericName: 'Thiopental', category: 'Anesthetic (Barbiturate)', dosages: ['2-5mg/kg (IV induction)'], routes: ['IV'], sideEffects: ['Respiratory depression', 'Hypotension', 'Laryngospasm', 'Tissue necrosis (extravasation)'], indications: ['Induction of anesthesia', 'Status epilepticus', 'Increased ICP'], contraindications: ['Porphyria', 'Status asthmaticus', 'Severe shock'], nursingConsiderations: ['Administer only by trained personnel', 'Monitor respiratory function', 'Avoid arterial injection (necrosis)'] },

  // Antispasmodics
  { name: 'Hyoscine Butylbromide', genericName: 'Scopolamine Butylbromide', category: 'Antispasmodic', dosages: ['10mg', '20mg'], routes: ['Oral', 'IV', 'IM', 'PR'], sideEffects: ['Dry mouth', 'Blurred vision', 'Constipation', 'Urinary retention'], indications: ['Abdominal cramps', 'Irritable bowel syndrome', 'Renal colic'], contraindications: ['Myasthenia gravis', 'Narrow-angle glaucoma', 'Obstruction'], nursingConsiderations: ['Do not use in patients with ileus', 'Monitor for anticholinergic effects', 'Caution in elderly'] },

  // Antidotes
  { name: 'N-Acetylcysteine', genericName: 'Acetylcysteine', category: 'Antidote/Mucolytic', dosages: ['600mg', '1200mg'], routes: ['IV', 'Oral', 'Inhalation'], sideEffects: ['Nausea', 'Rash', 'Anaphylactoid reaction (IV)', 'Bronchospasm'], indications: ['Paracetamol overdose', 'Mucolytic (COPD, cystic fibrosis)'], contraindications: ['Acetylcysteine allergy'], nursingConsiderations: ['Loading dose 150mg/kg in 200ml D5W over 1hr', 'Monitor for anaphylactoid reaction (flushing, rash)', 'IV protocol: 3-stage infusion over 21 hours'] },
  { name: 'Protamine Sulfate', genericName: 'Protamine', category: 'Antidote', dosages: ['1mg per 100U heparin'], routes: ['IV'], sideEffects: ['Hypotension', 'Bradycardia', 'Allergic reactions (fish allergy)'], indications: ['Heparin overdose reversal'], contraindications: ['Fish allergy (relative)'], nursingConsiderations: ['Dose based on heparin given in last 2-3 hours', 'Administer slowly (max 50mg in 10 min)', 'Monitor aPTT closely'] },
  { name: 'Deferoxamine', genericName: 'Desferrioxamine', category: 'Antidote/Chelating Agent', dosages: ['500mg', '1g', '2g'], routes: ['IV', 'IM', 'SC'], sideEffects: ['Hypotension', 'Rash', 'Infection risk (Yersinia)', 'Ototoxicity'], indications: ['Iron overdose', 'Iron overload (thalassemia)', 'Aluminum overload'], contraindications: ['Severe renal impairment (without dialysis)'], nursingConsiderations: ['Monitor iron levels', 'Urine will turn reddish (vin rose)', 'Monitor for infections'] },

  // Vaccines (Information only)
  { name: 'BCG Vaccine', genericName: 'Bacillus Calmette-Guerin', category: 'Vaccine', dosages: ['0.05ml (neonates)', '0.1ml (children/adults)'], routes: ['Intradermal'], sideEffects: ['Local ulceration', 'Lymphadenitis', 'Osteitis (rare)', 'Disseminated BCG (immunocompromised)'], indications: ['TB prevention', 'Bladder cancer (intravesical)'], contraindications: ['Immunosuppression', 'HIV infection', 'Pregnancy'], nursingConsiderations: ['Given intradermally on left deltoid', 'Do not massage after injection', 'Check for scar after 2-3 months', 'Store in refrigerator (2-8°C)'] },
];

export const getDrugs = (req, res) => {
  try {
    const { page = 1, limit = 50, search } = req.query;
    let filteredDrugs = drugs;

    if (search) {
      const searchTerm = search.toLowerCase();
      filteredDrugs = drugs.filter(drug =>
        drug.name.toLowerCase().includes(searchTerm) ||
        drug.genericName.toLowerCase().includes(searchTerm) ||
        drug.category.toLowerCase().includes(searchTerm) ||
        drug.indications.some(i => i.toLowerCase().includes(searchTerm))
      );
    }

    const startIndex = (page - 1) * limit;
    const endIndex = page * limit;
    const paginatedDrugs = filteredDrugs.slice(startIndex, endIndex);

    res.json({
      success: true,
      count: paginatedDrugs.length,
      total: filteredDrugs.length,
      page: parseInt(page),
      totalPages: Math.ceil(filteredDrugs.length / limit),
      data: paginatedDrugs
    });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Error fetching drugs', error: error.message });
  }
};

export const getDrugByName = (req, res) => {
  try {
    const { name } = req.params;
    const drug = drugs.find(d => d.name.toLowerCase() === name.toLowerCase());

    if (!drug) {
      return res.status(404).json({ success: false, message: 'Drug not found' });
    }

    res.json({ success: true, data: drug });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Error fetching drug', error: error.message });
  }
};

export const getDrugsByCategory = (req, res) => {
  try {
    const { category } = req.params;
    const filteredDrugs = drugs.filter(d =>
      d.category.toLowerCase().includes(category.toLowerCase())
    );

    if (filteredDrugs.length === 0) {
      return res.status(404).json({ success: false, message: 'No drugs found in this category' });
    }

    res.json({
      success: true,
      count: filteredDrugs.length,
      data: filteredDrugs
    });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Error fetching drugs by category', error: error.message });
  }
};
