const drugs = [
  { name: 'Paracetamol', genericName: 'Acetaminophen', category: 'Analgesic/Antipyretic', dosages: ['500mg', '650mg', '1g'], routes: ['Oral', 'IV'], sideEffects: ['Nausea', 'Rash', 'Liver toxicity (overdose)'], indications: ['Fever', 'Mild to moderate pain'], contraindications: ['Severe liver disease'], nursingConsiderations: ['Monitor liver function with prolonged use', 'Do not exceed 4g daily'] },
  { name: 'Amoxicillin', genericName: 'Amoxicillin', category: 'Antibiotic (Penicillin)', dosages: ['250mg', '500mg', '875mg'], routes: ['Oral', 'IV'], sideEffects: ['Diarrhea', 'Rash', 'Nausea'], indications: ['Bacterial infections', 'UTI', 'Respiratory infections'], contraindications: ['Penicillin allergy'], nursingConsiderations: ['Take with food to reduce GI upset', 'Complete full course'] },
  { name: 'Metronidazole', genericName: 'Metronidazole', category: 'Antibiotic/Antiprotozoal', dosages: ['200mg', '400mg', '500mg'], routes: ['Oral', 'IV', 'Topical'], sideEffects: ['Metallic taste', 'Nausea', 'Headache'], indications: ['Anaerobic infections', 'Trichomoniasis', 'Bacterial vaginosis'], contraindications: ['First trimester pregnancy'], nursingConsiderations: ['Avoid alcohol during treatment', 'May cause dark urine'] },
  { name: 'Artemether-Lumefantrine', genericName: 'Artemether/Lumefantrine', category: 'Antimalarial', dosages: ['20/120mg', '40/240mg', '80/480mg'], routes: ['Oral'], sideEffects: ['Headache', 'Dizziness', 'Nausea', 'Weakness'], indications: ['Uncomplicated malaria'], contraindications: ['Severe malaria (use IV artesunate)'], nursingConsiderations: ['Take with fatty food to improve absorption', 'Complete 3-day course'] },
  { name: 'Magnesium Sulfate', genericName: 'Magnesium Sulfate', category: 'Anticonvulsant/Electrolyte', dosages: ['1g', '2g', '4g', '10g'], routes: ['IV', 'IM'], sideEffects: ['Flushing', 'Drowsiness', 'Hypotension', 'Respiratory depression'], indications: ['Severe preeclampsia/eclampsia', 'Hypomagnesemia'], contraindications: ['Myasthenia gravis', 'Heart block'], nursingConsiderations: ['Monitor respiratory rate and deep tendon reflexes', 'Keep calcium gluconate as antidote'] },
  { name: 'Diazepam', genericName: 'Diazepam', category: 'Benzodiazepine', dosages: ['2mg', '5mg', '10mg'], routes: ['Oral', 'IV', 'Rectal'], sideEffects: ['Drowsiness', 'Dizziness', 'Ataxia', 'Dependence'], indications: ['Seizures', 'Anxiety', 'Muscle spasms'], contraindications: ['Acute narrow-angle glaucoma'], nursingConsiderations: ['Monitor respiratory depression with IV administration', 'Avoid alcohol'] },
  { name: 'Nifedipine', genericName: 'Nifedipine', category: 'Calcium Channel Blocker', dosages: ['10mg', '20mg', '30mg', '60mg'], routes: ['Oral'], sideEffects: ['Dizziness', 'Flushing', 'Headache', 'Peripheral edema'], indications: ['Hypertension', 'Preterm labor (tocolysis)'], contraindications: ['Hypotension'], nursingConsiderations: ['Monitor BP regularly', 'Avoid grapefruit juice'] },
  { name: 'Hydralazine', genericName: 'Hydralazine', category: 'Vasodilator', dosages: ['10mg', '25mg', '50mg'], routes: ['Oral', 'IV'], sideEffects: ['Headache', 'Tachycardia', 'Palpitations', 'Lupus-like syndrome'], indications: ['Hypertension', 'Severe preeclampsia'], contraindications: ['Coronary artery disease'], nursingConsiderations: ['Monitor HR and BP continuously during IV administration', 'May cause reflex tachycardia'] },
  { name: 'Oxytocin', genericName: 'Oxytocin', category: 'Uterotonic', dosages: ['10 units', '30 units'], routes: ['IV', 'IM'], sideEffects: ['Nausea', 'Vomiting', 'Water intoxication'], indications: ['Induction of labor', 'Postpartum hemorrhage prevention'], contraindications: ['Fetal distress', 'Cephalopelvic disproportion'], nursingConsiderations: ['Monitor uterine contractions and fetal heart rate', 'Have resuscitation equipment ready'] },
  { name: 'Heparin', genericName: 'Heparin', category: 'Anticoagulant', dosages: ['5000 units', '7500 units', '10000 units'], routes: ['IV', 'Subcutaneous'], sideEffects: ['Bleeding', 'Bruising', 'Thrombocytopenia'], indications: ['DVT prophylaxis', 'PE treatment', 'ACS'], contraindications: ['Active bleeding', 'Thrombocytopenia'], nursingConsiderations: ['Monitor aPTT', 'Have protamine sulfate as antidote', 'Avoid IM injections'] },
  { name: 'Insulin (Regular)', genericName: 'Regular Insulin', category: 'Antidiabetic', dosages: ['100 units/mL'], routes: ['Subcutaneous', 'IV'], sideEffects: ['Hypoglycemia', 'Weight gain', 'Injection site reactions'], indications: ['Diabetes mellitus Type 1 & 2', 'DKA'], contraindications: ['Hypoglycemia'], nursingConsiderations: ['Monitor blood glucose before administration', 'Rotate injection sites', 'Store in refrigerator'] },
  { name: 'Furosemide', genericName: 'Furosemide', category: 'Loop Diuretic', dosages: ['20mg', '40mg', '80mg', '120mg'], routes: ['Oral', 'IV'], sideEffects: ['Dehydration', 'Hypokalemia', 'Hypotension', 'Ototoxicity'], indications: ['Heart failure', 'Pulmonary edema', 'Hypertension'], contraindications: ['Anuria', 'Severe hypokalemia'], nursingConsiderations: ['Monitor electrolytes and renal function', 'Administer in morning to avoid nocturia'] },
  { name: 'Gentamicin', genericName: 'Gentamicin', category: 'Aminoglycoside Antibiotic', dosages: ['80mg', '120mg', '160mg'], routes: ['IV', 'IM'], sideEffects: ['Nephrotoxicity', 'Ototoxicity', 'Nausea'], indications: ['Serious Gram-negative infections', 'Sepsis'], contraindications: ['Myasthenia gravis'], nursingConsiderations: ['Monitor renal function and hearing', 'Check peak and trough levels', 'Hydrate well'] },
  { name: 'Salbutamol', genericName: 'Albuterol', category: 'Bronchodilator (Beta-agonist)', dosages: ['100mcg/puff', '2mg', '4mg'], routes: ['Inhalation', 'Oral', 'IV'], sideEffects: ['Tremor', 'Tachycardia', 'Nervousness'], indications: ['Asthma', 'COPD', 'Preterm labor (tocolysis)'], contraindications: ['Tachyarrhythmias'], nursingConsiderations: ['Monitor heart rate', 'Rinse mouth after inhalation'] },
  { name: 'Tetanus Toxoid', genericName: 'Tetanus Vaccine', category: 'Vaccine', dosages: ['0.5mL'], routes: ['IM'], sideEffects: ['Pain at injection site', 'Fever', 'Fatigue'], indications: ['Tetanus prophylaxis', 'Routine immunization'], contraindications: ['Severe allergic reaction to prior dose'], nursingConsiderations: ['Shake vial well before use', 'Have epinephrine available', 'Record lot number'] },
  { name: 'Vitamin C', genericName: 'Ascorbic Acid', category: 'Vitamin', dosages: ['100mg', '500mg', '1000mg'], routes: ['Oral', 'IV'], sideEffects: ['Diarrhea (high doses)', 'Nausea'], indications: ['Vitamin C deficiency', 'Scurvy', 'Wound healing'], contraindications: ['None significant'], nursingConsiderations: ['May enhance iron absorption', 'High doses may cause kidney stones in predisposed patients'] },
  { name: 'Loratadine', genericName: 'Loratadine', category: 'Antihistamine', dosages: ['10mg'], routes: ['Oral'], sideEffects: ['Drowsiness (rare)', 'Dry mouth', 'Headache'], indications: ['Allergic rhinitis', 'Urticaria'], contraindications: ['Severe liver disease'], nursingConsiderations: ['Non-sedating antihistamine', 'Take once daily'] },
  { name: 'Omeprazole', genericName: 'Omeprazole', category: 'Proton Pump Inhibitor', dosages: ['20mg', '40mg'], routes: ['Oral', 'IV'], sideEffects: ['Headache', 'Nausea', 'Diarrhea', 'Long-term fracture risk'], indications: ['GERD', 'Peptic ulcer', 'Stress ulcer prophylaxis'], contraindications: ['Long-term use without GI evaluation'], nursingConsiderations: ['Take before breakfast', 'Monitor magnesium levels with prolonged use'] },
  { name: 'Haloperidol', genericName: 'Haloperidol', category: 'Antipsychotic', dosages: ['0.5mg', '1mg', '2mg', '5mg'], routes: ['Oral', 'IM', 'IV'], sideEffects: ['Extrapyramidal symptoms', 'Drowsiness', 'QT prolongation'], indications: ['Psychosis', 'Acute agitation', 'Delirium'], contraindications: ['Parkinson\'s disease', 'QT prolongation'], nursingConsiderations: ['Monitor EPS', 'Check ECG for QT prolongation', 'Avoid concurrent CNS depressants'] },
  { name: 'Morphine', genericName: 'Morphine Sulfate', category: 'Opioid Analgesic', dosages: ['2mg', '5mg', '10mg', '15mg'], routes: ['Oral', 'IV', 'IM', 'Subcutaneous'], sideEffects: ['Respiratory depression', 'Nausea', 'Constipation', 'Dependence'], indications: ['Severe pain', 'Acute pulmonary edema'], contraindications: ['Respiratory depression', 'Paralytic ileus'], nursingConsiderations: ['Monitor respiratory rate and sedation', 'Naloxone is antidote', 'Assess pain regularly'] },
  { name: 'ART-LPV/r', genericName: 'Lopinavir/Ritonavir', category: 'Antiretroviral (HIV)', dosages: ['100/25mg', '200/50mg'], routes: ['Oral'], sideEffects: ['Diarrhea', 'Nausea', 'Hyperlipidemia', 'Hepatotoxicity'], indications: ['HIV infection'], contraindications: ['Severe hepatic impairment'], nursingConsiderations: ['Take with food', 'Monitor liver function and lipid profile', 'Adherence counseling'] },
  { name: 'Iron Dextran', genericName: 'Iron Dextran', category: 'Iron Supplement', dosages: ['100mg', '200mg', '500mg'], routes: ['IV', 'IM'], sideEffects: ['Anaphylaxis', 'Hypotension', 'Pain at injection site'], indications: ['Iron deficiency anemia (severe)', 'Chronic kidney disease'], contraindications: ['Hemochromatosis', 'Iron overload'], nursingConsiderations: ['Give test dose first', 'Monitor for anaphylaxis', 'Use Z-track for IM injection'] },
  { name: 'Dopamine', genericName: 'Dopamine', category: 'Inotropic/Vasopressor', dosages: ['200mg/5mL', '400mg/5mL'], routes: ['IV'], sideEffects: ['Tachycardia', 'Arrhythmias', 'Hypertension', 'Tissue necrosis (extravasation)'], indications: ['Shock', 'Hypotension', 'Heart failure'], contraindications: ['Hypovolemia (correct first)', 'Ventricular fibrillation'], nursingConsiderations: ['Titrate to BP response', 'Monitor IV site for extravasation', 'Use central line if possible'] },
  { name: 'Dexamethasone', genericName: 'Dexamethasone', category: 'Corticosteroid', dosages: ['2mg', '4mg', '8mg', '16mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Hyperglycemia', 'Immunosuppression', 'Weight gain', 'Osteoporosis'], indications: ['Inflammation', 'Cerebral edema', 'COVID-19 severe', 'Preterm labor (fetal lung maturity)'], contraindications: ['Systemic fungal infection'], nursingConsiderations: ['Monitor blood glucose', 'Taper dose gradually', 'Avoid live vaccines'] },
  { name: 'Lignocaine', genericName: 'Lidocaine', category: 'Local Anesthetic/Antiarrhythmic', dosages: ['1%', '2%', '5%'], routes: ['Topical', 'Local infiltration', 'IV'], sideEffects: ['Dizziness', 'Tremor', 'Seizures', 'Cardiac arrest'], indications: ['Local anesthesia', 'Ventricular arrhythmias'], contraindications: ['Heart block', 'Severe bradycardia'], nursingConsiderations: ['Do not exceed maximum dose', 'Use with caution in liver disease', 'Have resuscitation equipment ready'] },
  { name: 'Ibuprofen', genericName: 'Ibuprofen', category: 'NSAID', dosages: ['200mg', '400mg', '600mg', '800mg'], routes: ['Oral', 'IV'], sideEffects: ['GI irritation', 'Bleeding risk', 'Renal impairment', 'Dizziness'], indications: ['Pain', 'Inflammation', 'Fever', 'Arthritis'], contraindications: ['Peptic ulcer', 'Severe renal disease', 'Aspirin allergy'], nursingConsiderations: ['Take with food or milk', 'Monitor renal function', 'Avoid in dehydration'] },
  { name: 'Diclofenac', genericName: 'Diclofenac Sodium', category: 'NSAID', dosages: ['50mg', '75mg', '100mg'], routes: ['Oral', 'IM', 'Topical'], sideEffects: ['GI bleeding', 'Hepatotoxicity', 'Hypertension', 'Dizziness'], indications: ['Arthritis', 'Musculoskeletal pain', 'Dysmenorrhea', 'Post-operative pain'], contraindications: ['Active peptic ulcer', 'Severe heart failure', 'Third trimester pregnancy'], nursingConsiderations: ['Administer with food', 'Monitor LFTs', 'Short-term use preferred'] },
  { name: 'Tramadol', genericName: 'Tramadol HCl', category: 'Opioid Analgesic', dosages: ['50mg', '100mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Nausea', 'Dizziness', 'Seizures', 'Dependence', 'Serotonin syndrome'], indications: ['Moderate to severe pain', 'Chronic pain'], contraindications: ['Seizure disorder', 'MAOI use', 'Severe respiratory depression'], nursingConsiderations: ['Lower seizure threshold', 'Taper to avoid withdrawal', 'Avoid with SSRIs'] },
  { name: 'Pentazocine', genericName: 'Pentazocine', category: 'Opioid Agonist-Antagonist', dosages: ['30mg', '50mg'], routes: ['IM', 'IV', 'Oral'], sideEffects: ['Dizziness', 'Nausea', 'Hallucinations', 'Respiratory depression'], indications: ['Moderate to severe pain', 'Obstetric analgesia'], contraindications: ['Opioid dependence', 'Severe respiratory depression'], nursingConsiderations: ['May cause withdrawal in opioid-dependent patients', 'Monitor respiratory rate', 'Can cause hallucinations'] },
  { name: 'Ceftriaxone', genericName: 'Ceftriaxone', category: 'Cephalosporin Antibiotic', dosages: ['250mg', '500mg', '1g', '2g'], routes: ['IV', 'IM'], sideEffects: ['Diarrhea', 'Rash', 'Elevated LFTs', 'Biliary sludge'], indications: ['Sepsis', 'Pneumonia', 'Meningitis', 'Gonorrhea', 'UTI'], contraindications: ['Cephalosporin allergy', 'Neonatal hyperbilirubinemia'], nursingConsiderations: ['Do not co-administer with calcium-containing IV fluids', 'Monitor for superinfection'] },
  { name: 'Ciprofloxacin', genericName: 'Ciprofloxacin', category: 'Fluoroquinolone Antibiotic', dosages: ['250mg', '500mg', '750mg'], routes: ['Oral', 'IV'], sideEffects: ['Nausea', 'Tendon rupture', 'QT prolongation', 'CNS effects'], indications: ['UTI', 'Typhoid fever', 'GI infections', 'Respiratory infections'], contraindications: ['Children <18 (avoid)', 'Tendon disorders', 'Epilepsy'], nursingConsiderations: ['Avoid antacids within 2 hours', 'Hydrate well', 'Monitor for tendon pain'] },
  { name: 'Azithromycin', genericName: 'Azithromycin', category: 'Macrolide Antibiotic', dosages: ['250mg', '500mg'], routes: ['Oral', 'IV'], sideEffects: ['Nausea', 'Diarrhea', 'QT prolongation', 'Abdominal pain'], indications: ['Respiratory infections', 'STIs', 'Skin infections'], contraindications: ['QT prolongation', 'Severe liver disease'], nursingConsiderations: ['Take on empty stomach', 'Monitor ECG if at risk', 'Complete full course'] },
  { name: 'Cloxacillin', genericName: 'Cloxacillin', category: 'Antibiotic (Penicillinase-resistant)', dosages: ['250mg', '500mg', '1g'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Nausea', 'Diarrhea', 'Rash', 'Hepatotoxicity'], indications: ['Staphylococcal infections', 'Cellulitis', 'Wound infections'], contraindications: ['Penicillin allergy'], nursingConsiderations: ['Take on empty stomach', 'Monitor LFTs', 'Check for cross-allergy'] },
  { name: 'Metronidazole IV', genericName: 'Metronidazole', category: 'Antibiotic (Anaerobic)', dosages: ['500mg/100mL'], routes: ['IV'], sideEffects: ['Metallic taste', 'Nausea', 'Headache', 'Seizures (high dose)'], indications: ['Severe anaerobic infections', 'Pelvic inflammatory disease', 'Intra-abdominal infections'], contraindications: ['First trimester pregnancy', 'CNS disorders'], nursingConsiderations: ['Infuse slowly', 'Monitor for neurotoxicity', 'Avoid alcohol'] },
  { name: 'Amlodipine', genericName: 'Amlodipine Besylate', category: 'Calcium Channel Blocker', dosages: ['5mg', '10mg'], routes: ['Oral'], sideEffects: ['Peripheral edema', 'Dizziness', 'Flushing', 'Palpitations'], indications: ['Hypertension', 'Angina'], contraindications: ['Severe hypotension'], nursingConsiderations: ['Monitor BP and HR', 'Check for ankle edema', 'Avoid grapefruit juice'] },
  { name: 'Lisinopril', genericName: 'Lisinopril', category: 'ACE Inhibitor', dosages: ['5mg', '10mg', '20mg'], routes: ['Oral'], sideEffects: ['Cough', 'Hyperkalemia', 'Angioedema', 'Hypotension'], indications: ['Hypertension', 'Heart failure', 'Diabetic nephropathy'], contraindications: ['Pregnancy', 'Angioedema history', 'Renal artery stenosis'], nursingConsiderations: ['Monitor BP, K+, renal function', 'Avoid potassium supplements', 'Report cough'] },
  { name: 'Digoxin', genericName: 'Digoxin', category: 'Cardiac Glycoside', dosages: ['0.125mg', '0.25mg'], routes: ['Oral', 'IV'], sideEffects: ['Nausea', 'Bradycardia', 'Arrhythmias', 'Visual disturbances'], indications: ['Heart failure', 'Atrial fibrillation'], contraindications: ['Heart block', 'Ventricular tachycardia'], nursingConsiderations: ['Monitor HR before administration', 'Check digoxin levels', 'Hold if HR <60'] },
  { name: 'Atenolol', genericName: 'Atenolol', category: 'Beta Blocker', dosages: ['25mg', '50mg', '100mg'], routes: ['Oral'], sideEffects: ['Bradycardia', 'Fatigue', 'Cold extremities', 'Bronchospasm'], indications: ['Hypertension', 'Angina', 'Post-MI', 'Migraine prophylaxis'], contraindications: ['Asthma', 'Heart block', 'Severe bradycardia'], nursingConsiderations: ['Monitor HR and BP', 'Do not stop abruptly', 'Use with caution in diabetes'] },
  { name: 'Methyldopa', genericName: 'Methyldopa', category: 'Central Alpha Agonist', dosages: ['250mg', '500mg'], routes: ['Oral', 'IV'], sideEffects: ['Drowsiness', 'Dry mouth', 'Hemolytic anemia', 'Edema'], indications: ['Hypertension in pregnancy', 'Chronic hypertension'], contraindications: ['Active liver disease', 'Depression'], nursingConsiderations: ['Monitor LFTs and CBC', 'May cause positive Coombs test', 'Safe in pregnancy'] },
  { name: 'Carbamazepine', genericName: 'Carbamazepine', category: 'Anticonvulsant', dosages: ['200mg', '400mg'], routes: ['Oral'], sideEffects: ['Dizziness', 'Diplopia', 'Hyponatremia', 'Stevens-Johnson syndrome', 'Bone marrow suppression'], indications: ['Epilepsy (partial, tonic-clonic)', 'Trigeminal neuralgia', 'Bipolar disorder'], contraindications: ['History of bone marrow depression', 'AV block'], nursingConsiderations: ['Monitor CBC and LFTs', 'Check sodium levels', 'Auto-induces metabolism'] },
  { name: 'Sodium Valproate', genericName: 'Valproic Acid', category: 'Anticonvulsant', dosages: ['200mg', '500mg'], routes: ['Oral', 'IV'], sideEffects: ['Hepatotoxicity', 'Drowsiness', 'Tremor', 'Weight gain', 'Thrombocytopenia'], indications: ['Epilepsy (all types)', 'Migraine prophylaxis', 'Bipolar disorder'], contraindications: ['Severe liver disease', 'Pregnancy (avoid)'], nursingConsiderations: ['Monitor LFTs and platelets', 'Hepatotoxicity risk in children <2', 'Avoid in pregnancy'] },
  { name: 'Phenytoin', genericName: 'Phenytoin', category: 'Anticonvulsant', dosages: ['100mg', '300mg'], routes: ['Oral', 'IV'], sideEffects: ['Nystagmus', 'Ataxia', 'Gingival hyperplasia', 'Stevens-Johnson syndrome'], indications: ['Epilepsy (generalized tonic-clonic, partial)', 'Status epilepticus'], contraindications: ['Sinus bradycardia', 'AV block'], nursingConsiderations: ['Monitor drug levels', 'Good oral hygiene for gums', 'IV extravasation causes tissue necrosis'] },
  { name: 'Aminophylline', genericName: 'Aminophylline', category: 'Bronchodilator (Xanthine)', dosages: ['100mg', '250mg'], routes: ['IV', 'Oral'], sideEffects: ['Nausea', 'Tachycardia', 'Insomnia', 'Seizures'], indications: ['Severe asthma exacerbation', 'COPD'], contraindications: ['Seizure disorder', 'Peptic ulcer'], nursingConsiderations: ['Monitor theophylline levels', 'Slow IV infusion', 'Avoid caffeine'] },
  { name: 'Beclomethasone', genericName: 'Beclomethasone Dipropionate', category: 'Inhaled Corticosteroid', dosages: ['50mcg/puff', '100mcg/puff', '250mcg/puff'], routes: ['Inhalation'], sideEffects: ['Oral thrush', 'Hoarseness', 'Sore throat'], indications: ['Persistent asthma', 'Allergic rhinitis'], contraindications: ['Acute asthma attack (not for rescue)'], nursingConsiderations: ['Rinse mouth after use', 'Use spacer device', 'Regular use required for control'] },
  { name: 'Adrenaline', genericName: 'Epinephrine', category: 'Vasopressor/Anaphylaxis', dosages: ['1mg/mL (1:1000)', '0.1mg/mL (1:10,000)'], routes: ['IM', 'IV', 'Subcutaneous', 'Endotracheal'], sideEffects: ['Tachycardia', 'Hypertension', 'Arrhythmias', 'Anxiety'], indications: ['Anaphylaxis', 'Cardiac arrest', 'Severe asthma'], contraindications: ['None in emergency situations'], nursingConsiderations: ['IM vastus lateralis for anaphylaxis', 'Monitor cardiac rhythm', 'Check expiration date'] },
  { name: 'Atropine', genericName: 'Atropine Sulfate', category: 'Anticholinergic', dosages: ['0.6mg', '1mg', '2mg'], routes: ['IV', 'IM', 'Endotracheal'], sideEffects: ['Dry mouth', 'Blurred vision', 'Tachycardia', 'Urinary retention'], indications: ['Bradycardia', 'Organophosphate poisoning', 'Pre-anesthesia'], contraindications: ['Glaucoma', 'Myasthenia gravis'], nursingConsiderations: ['Monitor HR after administration', 'Can cause heat intolerance', 'Use with caution in elderly'] },
  { name: 'Naloxone', genericName: 'Naloxone HCl', category: 'Opioid Antagonist', dosages: ['0.4mg', '2mg'], routes: ['IV', 'IM', 'Intranasal'], sideEffects: ['Opioid withdrawal', 'Hypertension', 'Arrhythmias', 'Seizures'], indications: ['Opioid overdose', 'Respiratory depression from opioids'], contraindications: ['None in emergency overdose'], nursingConsiderations: ['Short half-life — may need repeat doses', 'Monitor for re-sedation', 'Have emergency equipment ready'] },
  { name: 'Misoprostol', genericName: 'Misoprostol', category: 'Prostaglandin', dosages: ['200mcg', '400mcg', '600mcg', '800mcg'], routes: ['Oral', 'Sublingual', 'Vaginal', 'Rectal'], sideEffects: ['Uterine cramps', 'Nausea', 'Diarrhea', 'Fever'], indications: ['Postpartum hemorrhage', 'Induction of labor', 'Medical abortion', 'GI ulcer prevention'], contraindications: ['Previous C-section (caution)', 'Allergy'], nursingConsiderations: ['Monitor uterine tone and bleeding', 'Document routes carefully', 'Can cause hyperstimulation'] },
  { name: 'Ergometrine', genericName: 'Ergometrine Maleate', category: 'Uterotonic', dosages: ['0.2mg', '0.5mg'], routes: ['IV', 'IM'], sideEffects: ['Hypertension', 'Nausea', 'Vomiting', 'Uterine hypertonus'], indications: ['Postpartum hemorrhage', 'Third stage of labor'], contraindications: ['Hypertension', 'Preeclampsia', 'Peripheral vascular disease'], nursingConsiderations: ['Avoid in hypertensive patients', 'Monitor BP and uterine tone', 'Do not use in first stage of labor'] },
  { name: 'Rifampicin', genericName: 'Rifampin', category: 'Antitubercular', dosages: ['150mg', '300mg', '450mg', '600mg'], routes: ['Oral', 'IV'], sideEffects: ['Hepatotoxicity', 'Red-orange discoloration of fluids', 'Rash', 'GI upset'], indications: ['Tuberculosis', 'Leprosy', 'Meningococcal prophylaxis'], contraindications: ['Severe liver disease', 'Porphyria'], nursingConsiderations: ['Take on empty stomach', 'Warn about red urine/tears', 'Monitor LFTs', 'Counselling on adherence'] },
  { name: 'Isoniazid', genericName: 'Isoniazid (INH)', category: 'Antitubercular', dosages: ['100mg', '300mg'], routes: ['Oral', 'IM'], sideEffects: ['Hepatotoxicity', 'Peripheral neuropathy', 'Rash', 'Pyridoxine deficiency'], indications: ['Tuberculosis (treatment and prophylaxis)'], contraindications: ['Acute liver disease', 'INH-induced hepatitis history'], nursingConsiderations: ['Give with pyridoxine (Vitamin B6)', 'Monitor LFTs', 'Avoid alcohol', 'Check for neuropathy'] },
  { name: 'Tenofovir', genericName: 'Tenofovir Disoproxil', category: 'Antiretroviral (NRTI)', dosages: ['300mg'], routes: ['Oral'], sideEffects: ['Renal toxicity', 'Bone density loss', 'Nausea', 'Headache'], indications: ['HIV infection', 'Hepatitis B'], contraindications: ['Severe renal impairment (CrCl <30)'], nursingConsiderations: ['Monitor renal function', 'Check CrCl before use', 'Avoid with nephrotoxic drugs'] },
  { name: 'Dolutegravir', genericName: 'Dolutegravir Sodium', category: 'Antiretroviral (INSTI)', dosages: ['50mg'], routes: ['Oral'], sideEffects: ['Insomnia', 'Headache', 'Weight gain', 'Nausea'], indications: ['HIV infection (first-line preferred)'], contraindications: ['Co-administration with dofetilide'], nursingConsiderations: ['Take without regard to food', 'Monitor for IRIS', 'Well tolerated — few interactions'] },
  { name: 'Efavirenz', genericName: 'Efavirenz', category: 'Antiretroviral (NNRTI)', dosages: ['200mg', '600mg'], routes: ['Oral'], sideEffects: ['Dizziness', 'Vivid dreams', 'Rash', 'Hepatotoxicity', 'Suicidal ideation'], indications: ['HIV infection'], contraindications: ['First trimester pregnancy (avoid)', 'Severe psychiatric illness'], nursingConsiderations: ['Take on empty stomach at bedtime', 'Report mood changes', 'Monitor LFTs'] },
  { name: 'Quinine', genericName: 'Quinine Sulfate', category: 'Antimalarial', dosages: ['300mg', '600mg'], routes: ['Oral', 'IV'], sideEffects: ['Cinchonism (tinnitus, headache, N&V)', 'QT prolongation', 'Hypoglycemia'], indications: ['Severe malaria (IV)', 'Uncomplicated malaria (second-line)'], contraindications: ['QT prolongation', 'G6PD deficiency (caution)'], nursingConsiderations: ['Monitor blood glucose', 'Check ECG for QT prolongation', 'IV infusion over 4 hours'] },
  { name: 'Chloroquine', genericName: 'Chloroquine Phosphate', category: 'Antimalarial', dosages: ['250mg', '500mg'], routes: ['Oral'], sideEffects: ['Nausea', 'Pruritus', 'Retinopathy (long-term)', 'Headache'], indications: ['Malaria (sensitive areas)', 'Autoimmune diseases (off-label)'], contraindications: ['Retinal disease', 'Porphyria'], nursingConsiderations: ['Now resistance widespread in Africa', 'Screen for G6PD deficiency', 'Eye exam for long-term use'] },
  { name: 'Doxycycline', genericName: 'Doxycycline Hyclate', category: 'Tetracycline Antibiotic', dosages: ['100mg'], routes: ['Oral', 'IV'], sideEffects: ['Photosensitivity', 'GI upset', 'Esophageal ulceration', 'Tooth discoloration'], indications: ['Malaria prophylaxis', 'Acne', 'Respiratory infections', 'STIs'], contraindications: ['Children <8 years', 'Pregnancy'], nursingConsiderations: ['Take with full glass of water', 'Avoid sun exposure', 'Not with dairy/antacids'] },
  { name: 'Metoclopramide', genericName: 'Metoclopramide HCl', category: 'Antiemetic/Prokinetic', dosages: ['10mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Drowsiness', 'Dystonia', 'Diarrhea', 'Fatigue'], indications: ['Nausea and vomiting', 'Gastroparesis', 'Migraine (adjunct)'], contraindications: ['GI obstruction', 'Parkinson\'s disease', 'Recent GI surgery'], nursingConsiderations: ['Can cause extrapyramidal effects', 'Max 5-day use', 'Monitor for tardive dyskinesia'] },
  { name: 'Hyoscine (Buscopan)', genericName: 'Hyoscine Butylbromide', category: 'Antispasmodic', dosages: ['10mg', '20mg'], routes: ['Oral', 'IM', 'IV'], sideEffects: ['Dry mouth', 'Blurred vision', 'Tachycardia', 'Urinary retention'], indications: ['Abdominal cramps', 'IBS', 'Renal colic', 'Dysmenorrhea'], contraindications: ['Glaucoma', 'Myasthenia gravis', 'GI obstruction'], nursingConsiderations: ['Not for long-term use', 'Monitor for anticholinergic effects'] },
  { name: 'Loperamide', genericName: 'Loperamide HCl', category: 'Antidiarrheal', dosages: ['2mg'], routes: ['Oral'], sideEffects: ['Constipation', 'Dizziness', 'Dry mouth', 'Nausea'], indications: ['Acute and chronic diarrhea'], contraindications: ['Dysentery (bloody diarrhea)', 'C. difficile colitis', 'GI obstruction'], nursingConsiderations: ['Stop if no improvement in 48hrs', 'Hydrate aggressively', 'Not for children <6'] },
  { name: 'Lactulose', genericName: 'Lactulose', category: 'Osmotic Laxative', dosages: ['15mL', '30mL'], routes: ['Oral'], sideEffects: ['Bloating', 'Flatulence', 'Abdominal cramps', 'Diarrhea'], indications: ['Constipation', 'Hepatic encephalopathy'], contraindications: ['Galactosemia', 'GI obstruction'], nursingConsiderations: ['Onset 24-48hrs', 'Monitor for electrolyte imbalance', 'May mix with juice'] },
  { name: 'Sodium Bicarbonate', genericName: 'Sodium Bicarbonate', category: 'Alkalizing Agent', dosages: ['8.4% (50mEq/50mL)', '4.2% (25mEq/50mL)'], routes: ['IV'], sideEffects: ['Metabolic alkalosis', 'Hypernatremia', 'Extravasation necrosis', 'Hypocalcemia'], indications: ['Metabolic acidosis', 'Cardiac arrest (hyperkalemia)', 'TCA overdose'], contraindications: ['Metabolic alkalosis', 'Hypocalcemia'], nursingConsiderations: ['Do not mix with catecholamines', 'Monitor ABG and electrolytes', 'Check IV site carefully'] },
  { name: 'Vitamin B Complex', genericName: 'Thiamine/B6/B12', category: 'Vitamin Supplement', dosages: ['1mL (IM)', '1 tablet (Oral)'], routes: ['IM', 'Oral'], sideEffects: ['Rare allergic reactions', 'Burning at injection site'], indications: ['Vitamin B deficiency', 'Alcoholism', 'Peripheral neuropathy', 'Anemia prevention'], contraindications: ['None significant'], nursingConsiderations: ['IM injection deeply into gluteal muscle', 'Can cause red urine (B12)', 'Store in cool dark place'] },
  { name: 'Ferrous Sulfate', genericName: 'Ferrous Sulfate', category: 'Iron Supplement', dosages: ['200mg (65mg Fe)', '300mg (95mg Fe)'], routes: ['Oral'], sideEffects: ['Constipation', 'Dark stools', 'Nausea', 'GI irritation'], indications: ['Iron deficiency anemia', 'Pregnancy supplementation'], contraindications: ['Hemochromatosis', 'Thalassemia (without iron deficiency)'], nursingConsiderations: ['Take with vitamin C for absorption', 'Take between meals', 'Stool will turn black'] },
  { name: 'Folic Acid', genericName: 'Folic Acid', category: 'Vitamin Supplement', dosages: ['0.4mg', '1mg', '5mg'], routes: ['Oral', 'IM', 'IV'], sideEffects: ['Rare allergic reactions'], indications: ['Megaloblastic anemia', 'Pregnancy (neural tube defect prevention)', 'Antifolate drug therapy'], contraindications: ['Vitamin B12 deficiency (untreated)'], nursingConsiderations: ['Rule out B12 deficiency before use', 'Start before conception for NTD prevention', 'Monitor RBC indices'] },
  { name: 'Ranitidine', genericName: 'Ranitidine HCl', category: 'H2 Antagonist', dosages: ['150mg', '300mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Headache', 'Dizziness', 'GI upset'], indications: ['Peptic ulcer', 'GERD', 'Stress ulcer prophylaxis'], contraindications: ['Severe renal impairment', 'Porphyria'], nursingConsiderations: ['Administer with or without food', 'Monitor renal function', 'Check for drug interactions'] },
  { name: 'Prednisolone', genericName: 'Prednisolone', category: 'Corticosteroid', dosages: ['5mg', '10mg', '20mg', '40mg'], routes: ['Oral', 'IV'], sideEffects: ['Hyperglycemia', 'Osteoporosis', 'Weight gain', 'Immunosuppression', 'Adrenal suppression'], indications: ['Asthma exacerbation', 'Allergic reactions', 'Autoimmune disorders', 'COPD'], contraindications: ['Systemic fungal infection', 'Live vaccines'], nursingConsiderations: ['Taper gradually', 'Monitor blood glucose', 'Give with food', 'Never stop abruptly'] },
  { name: 'Spironolactone', genericName: 'Spironolactone', category: 'Potassium-Sparing Diuretic', dosages: ['25mg', '50mg', '100mg'], routes: ['Oral'], sideEffects: ['Hyperkalemia', 'Gynecomastia', 'Dizziness', 'Menstrual irregularities'], indications: ['Heart failure', 'Hypertension', 'Ascites in cirrhosis', 'Primary aldosteronism'], contraindications: ['Hyperkalemia', 'Addison\'s disease', 'Severe renal impairment'], nursingConsiderations: ['Monitor K+ and renal function', 'Avoid K+ supplements', 'Report gynecomastia'] },
  { name: 'Bisoprolol', genericName: 'Bisoprolol Fumarate', category: 'Beta Blocker', dosages: ['2.5mg', '5mg', '10mg'], routes: ['Oral'], sideEffects: ['Bradycardia', 'Fatigue', 'Dizziness', 'Bronchospasm'], indications: ['Heart failure', 'Hypertension', 'Angina'], contraindications: ['Severe bradycardia', 'Heart block', 'Uncontrolled asthma'], nursingConsiderations: ['Start low, go slow', 'Monitor HR and BP', 'Do not stop abruptly', 'Use in HFrEF'] },
  { name: 'Warfarin', genericName: 'Warfarin Sodium', category: 'Anticoagulant', dosages: ['1mg', '2mg', '3mg', '5mg'], routes: ['Oral'], sideEffects: ['Bleeding', 'Bruising', 'Skin necrosis', 'Purple toes syndrome'], indications: ['DVT/PE treatment and prophylaxis', 'Atrial fibrillation', 'Mechanical heart valves'], contraindications: ['Active bleeding', 'Pregnancy (avoid)', 'Severe hepatic impairment'], nursingConsiderations: ['Monitor INR (target 2-3)', 'Vitamin K is antidote', 'Watch diet (vitamin K intake)', 'Educate about bleeding signs'] },
  { name: 'Enoxaparin', genericName: 'Enoxaparin Sodium', category: 'Low Molecular Weight Heparin', dosages: ['20mg', '40mg', '60mg', '80mg', '100mg'], routes: ['Subcutaneous'], sideEffects: ['Bleeding', 'Bruising at injection site', 'Thrombocytopenia'], indications: ['DVT prophylaxis', 'PE treatment', 'ACS'], contraindications: ['Active bleeding', 'Thrombocytopenia (HIT)'], nursingConsiderations: ['Do not expel air bubble from syringe', 'Rotate injection sites', 'Monitor anti-Xa if needed', 'Protamine partial reversal'] },
  { name: 'Ceftazidime', genericName: 'Ceftazidime', category: 'Cephalosporin (3rd Gen)', dosages: ['500mg', '1g', '2g'], routes: ['IV', 'IM'], sideEffects: ['Diarrhea', 'Rash', 'Eosinophilia', 'Pseudomembranous colitis'], indications: ['Pseudomonas infections', 'Meningitis', 'Febrile neutropenia'], contraindications: ['Cephalosporin allergy'], nursingConsiderations: ['Monitor renal function', 'Dose adjust in renal impairment', 'IV infusion over 15-30 mins'] },
  { name: 'Meropenem', genericName: 'Meropenem', category: 'Carbapenem Antibiotic', dosages: ['500mg', '1g'], routes: ['IV'], sideEffects: ['Nausea', 'Diarrhea', 'Rash', 'Seizures (rare)', 'Pseudomembranous colitis'], indications: ['Severe hospital-acquired infections', 'Intra-abdominal infections', 'Meningitis'], contraindications: ['Carbapenem allergy', 'Beta-lactam severe allergy (caution)'], nursingConsiderations: ['Infuse over 15-30 mins', 'Monitor renal function', 'Reserve for multi-drug resistant infections'] },
  { name: 'Mannitol', genericName: 'Mannitol', category: 'Osmotic Diuretic', dosages: ['20% solution (250mL)', '500mL'], routes: ['IV'], sideEffects: ['Dehydration', 'Electrolyte imbalance', 'Heart failure exacerbation', 'Renal injury'], indications: ['Cerebral edema', 'Raised intracranial pressure', 'Oliguric renal failure prevention'], contraindications: ['Anuria', 'Heart failure', 'Pulmonary edema'], nursingConsiderations: ['Filter before use', 'Monitor I&O and electrolytes', 'Check for crystals in solution'] },
  { name: 'Propranolol', genericName: 'Propranolol HCl', category: 'Beta Blocker', dosages: ['10mg', '20mg', '40mg', '80mg'], routes: ['Oral', 'IV'], sideEffects: ['Bradycardia', 'Bronchospasm', 'Cold extremities', 'Sleep disturbances', 'Mask hypoglycemia'], indications: ['Hypertension', 'Migraine prophylaxis', 'Performance anxiety', 'Thyrotoxicosis', 'Essential tremor'], contraindications: ['Asthma', 'Heart block', 'Severe bradycardia'], nursingConsiderations: ['Do not stop abruptly', 'Monitor HR and BP', 'Use with caution in diabetes', 'Avoid in asthma'] },
  { name: 'Ketamine', genericName: 'Ketamine HCl', category: 'Dissociative Anesthetic', dosages: ['10mg/mL', '50mg/mL', '100mg/mL'], routes: ['IV', 'IM', 'Intranasal'], sideEffects: ['Hallucinations', 'Hypertension', 'Nystagmus', 'Increased ICP', 'Emergence reactions'], indications: ['Induction of anesthesia', 'Procedural sedation', 'Treatment-resistant depression', 'Pain management'], contraindications: ['Hypertension (severe)', 'Increased ICP', 'Schizophrenia'], nursingConsiderations: ['Monitor vitals closely', 'Use in monitored setting', 'Emergence reactions common in adults', 'Have resuscitation equipment ready'] },
  { name: 'Pethidine', genericName: 'Meperidine HCl', category: 'Opioid Analgesic', dosages: ['50mg', '100mg'], routes: ['IM', 'IV', 'Oral'], sideEffects: ['Respiratory depression', 'Nausea', 'Dizziness', 'Seizures (normeperidine)', 'Dependence'], indications: ['Moderate to severe pain', 'Post-operative shivering', 'Rigors'], contraindications: ['MAOI use (within 14 days)', 'Seizure disorder'], nursingConsiderations: ['Not for chronic pain', 'Normeperidine metabolite can cause seizures', 'Monitor respiratory rate', 'Short-term use only'] },
];

export async function getDrugs(req, res) {
  try {
    const { search } = req.query;
    let result = drugs;
    if (search) {
      const q = search.toLowerCase();
      result = drugs.filter(d => d.name.toLowerCase().includes(q) || d.genericName.toLowerCase().includes(q) || d.category.toLowerCase().includes(q));
    }
    res.json(result.slice(0, 50));
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}

export async function getDrugByName(req, res) {
  try {
    const drug = drugs.find(d => d.name.toLowerCase() === req.params.name.toLowerCase());
    if (!drug) return res.status(404).json({ error: 'Drug not found' });
    res.json(drug);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}
