const drugs = [
  { name: 'Paracetamol', genericName: 'Acetaminophen', category: 'Analgesic/Antipyretic', dosages: ['500mg', '650mg', '1g'], routes: ['Oral', 'IV'], sideEffects: ['Nausea', 'Rash', 'Liver toxicity (overdose)'], indications: ['Fever', 'Mild to moderate pain'], contraindications: ['Severe liver disease'], nursingConsiderations: ['Monitor liver function with prolonged use', 'Do not exceed 4g daily'] },
  { name: 'Amoxicillin', genericName: 'Amoxicillin', category: 'Antibiotic (Penicillin)', dosages: ['250mg', '500mg', '875mg'], routes: ['Oral', 'IV'], sideEffects: ['Diarrhea', 'Rash', 'Nausea'], indications: ['Bacterial infections', 'UTI', 'Respiratory infections'], contraindications: ['Penicillin allergy'], nursingConsiderations: ['Take with food to reduce GI upset', 'Complete full course'] },
  { name: 'Metronidazole', genericName: 'Metronidazole', category: 'Antibiotic/Antiprotozoal', dosages: ['200mg', '400mg', '500mg'], routes: ['Oral', 'IV', 'Topical'], sideEffects: ['Metallic taste', 'Nausea', 'Headache'], indications: ['Anaerobic infections', 'Trichomoniasis', 'Bacterial vaginosis'], contraindications: ['First trimester pregnancy'], nursingConsiderations: ['Avoid alcohol during treatment', 'May cause dark urine'] },
  { name: 'Artemether-Lumefantrine', genericName: 'Artemether/Lumefantrine', category: 'Antimalarial', dosages: ['20/120mg', '40/240mg', '80/480mg'], routes: ['Oral'], sideEffects: ['Headache', 'Dizziness', 'Nausea', 'Weakness'], indications: ['Uncomplicated malaria'], contraindications: ['Severe malaria (use IV artesunate)'], nursingConsiderations: ['Take with fatty food to improve absorption', 'Complete 3-day course'] },
  { name: 'Magnesium Sulfate', genericName: 'Magnesium Sulfate', category: 'Anticonvulsant/Electrolyte', dosages: ['1g', '2g', '4g', '10g'], routes: ['IV', 'IM'], sideEffects: ['Flushing', 'Drowsiness', 'Hypotension', 'Respiratory depression'], indications: ['Severe preeclampsia/eclampsia', 'Hypomagnesemia'], contraindications: ['Myasthenia gravis', 'Heart block'], nursingConsiderations: ['Monitor respiratory rate and deep tendon reflexes', 'Keep calcium gluconate as antidote'] },
  { name: 'Diazepam', genericName: 'Diazepam', category: 'Benzodiazepine', dosages: ['2mg', '5mg', '10mg'], routes: ['Oral', 'IV', 'Rectal'], sideEffects: ['Drowsiness', 'Dizziness', 'Ataxia', 'Dependence'], indications: ['Seizures', 'Anxiety', 'Muscle spasms'], contraindications: ['Acute narrow-angle glaucoma'], nursingConsiderations: ['Monitor respiratory depression with IV administration', 'Avoid alcohol'] },
  { name: 'Nifedipine', genericName: 'Nifedipine', category: 'Calcium Channel Blocker', dosages: ['10mg', '20mg', '30mg', '60mg'], routes: ['Oral'], sideEffects: ['Dizziness', 'Flushing', 'Headache', 'Peripheral edema'], indications: ['Hypertension', 'Preterm labor (tocolysis)'], contraindications: ['Hypotension'], nursingConsiderations: ['Monitor BP regularly', 'Avoid grapefruit juice'] },
  { name: 'Hydralazine', genericName: 'Hydralazine', category: 'Vasodilator', dosages: ['10mg', '25mg', '50mg'], routes: ['Oral', 'IV'], sideEffects: ['Headache', 'Tachycardia', 'Palpitations', 'Lupus-like syndrome'], indications: ['Hypertension', 'Severe preeclampsia'], contraindications: ['Coronary artery disease'], nursingConsiderations: ['Monitor HR and BP continuously during IV administration', 'May cause reflex tachycardia'] },
  { name: 'Oxytocin', genericName: 'Oxytocin', category: 'Uterotonic', dosages: ['10 units', '30 units'], routes: ['IV', 'IM'], sideEffects: ['Nausea', 'Vomiting', 'Water intoxication'], indications: ['Induction of labor', 'Postpartum hemorrhage prevention'], contraindications: ['Fetal distress', 'Cephalopelvic disproportion'], nursingConsiderations: ['Monitor uterine contractions and fetal heart rate', 'Have resuscitation equipment ready'] },
  { name: 'Heparin', genericName: 'Heparin', category: 'Anticoagulant', dosages: ['5000 units', '7500 units', '10000 units'], routes: ['IV', 'Subcutaneous'], sideEffects: ['Bleeding', 'Bruising', 'Thrombocytopenia'], indications: ['DVT prophylaxis', 'PE treatment', 'ACS'], contraindications: ['Active bleeding', 'Thrombocytopenia'], nursingConsiderations: ['Monitor aPTT', 'Have protamine sulfate as antidote', 'Avoid IM injections'] },
  { name: 'Insulin (Regular)', genericName: 'Regular Insulin', category: 'Antidiabetic', dosages: ['100 units/mL'], routes: ['Subcutaneous', 'IV'], sideEffects: ['Hypoglycemia', 'Weight gain', 'Injection site reactions'], indications: ['Diabetes mellitus Type 1 & 2', 'DKA'], contraindications: ['Hypoglycemia'], nursingConsiderations: ['Monitor blood glucose before administration', 'Rotate injection sites', 'Store in refrigerator'] },
  { name: 'Furosemide', genericName: 'Furosemide', category: 'Loop Diuretic', dosages: ['20mg', '40mg', '80mg', '120mg'], routes: ['Oral', 'IV'], sideEffects: ['Dehydration', 'Hypokalemia', 'Hypotension', 'Ototoxicity'], indications: ['Heart failure', 'Pulmonary edema', 'Hypertension'], contraindications: ['Anuria', 'Severe hypokalemia'], nursingConsiderations: ['Monitor electrolytes and renal function', 'Administer in morning to avoid nocturia'] },
  { name: 'Gentamicin', genericName: 'Gentamicin', category: 'Aminoglycoside Antibiotic', dosages: ['80mg', '120mg', '160mg'], routes: ['IV', 'IM'], sideEffects: ['Nephrotoxicity', 'Ototoxicity', 'Nausea'], indications: ['Serious Gram-negative infections', 'Sepsis'], contraindications: ['Myasthenia gravis'], nursingConsiderations: ['Monitor renal function and hearing', 'Check peak and trough levels', 'Hydrate well'] },
  { name: 'Salbutamol', genericName: 'Albuterol', category: 'Bronchodilator (Beta-agonist)', dosages: ['100mcg/puff', '2mg', '4mg'], routes: ['Inhalation', 'Oral', 'IV'], sideEffects: ['Tremor', 'Tachycardia', 'Nervousness'], indications: ['Asthma', 'COPD', 'Preterm labor (tocolysis)'], contraindications: ['Tachyarrhythmias'], nursingConsiderations: ['Monitor heart rate', 'Rinse mouth after inhalation'] },
  { name: 'Tetanus Toxoid', genericName: 'Tetanus Vaccine', category: 'Vaccine', dosages: ['0.5mL'], routes: ['IM'], sideEffects: ['Pain at injection site', 'Fever', 'Fatigue'], indications: ['Tetanus prophylaxis', 'Routine immunization'], contraindications: ['Severe allergic reaction to prior dose'], nursingConsiderations: ['Shake vial well before use', 'Have epinephrine available', 'Record lot number'] },
  { name: 'Vitamin C', genericName: 'Ascorbic Acid', category: 'Vitamin', dosages: ['100mg', '500mg', '1000mg'], routes: ['Oral', 'IV'], sideEffects: ['Diarrhea (high doses)', 'Nausea'], indications: ['Vitamin C deficiency', 'Scurvy', 'Wound healing'], contraindications: ['None significant'], nursingConsiderations: ['May enhance iron absorption', 'High doses may cause kidney stones in predisposed patients'] },
  { name: 'Loratadine', genericName: 'Loratadine', category: 'Antihistamine', dosages: ['10mg'], routes: ['Oral'], sideEffects: ['Drowsiness (rare)', 'Dry mouth', 'Headache'], indications: ['Allergic rhinitis', 'Urticaria'], contraindications: ['Severe liver disease'], nursingConsiderations: ['Non-sedating antihistamine', 'Take once daily'] },
  { name: 'Omeprazole', genericName: 'Omeprazole', category: 'Proton Pump Inhibitor', dosages: ['20mg', '40mg'], routes: ['Oral', 'IV'], sideEffects: ['Headache', 'Nausea', 'Diarrhea', 'Long-term fracture risk'], indications: ['GERD', 'Peptic ulcer', 'Stress ulcer prophylaxis'], contraindications: ['Long-term use without GI evaluation'], nursingConsiderations: ['Take before breakfast', 'Monitor magnesium levels with prolonged use'] },
  { name: 'Haloperidol', genericName: 'Haloperidol', category: 'Antipsychotic', dosages: ['0.5mg', '1mg', '2mg', '5mg'], routes: ['Oral', 'IM', 'IV'], sideEffects: ['Extrapyramidal symptoms', 'Drowsiness', 'QT prolongation'], indications: ['Psychosis', 'Acute agitation', 'Delirium'], contraindications: ['Parkinson\'s disease', 'QT prolongation'], nursingConsiderations: ['Monitor EPS', 'Check ECG for QT prolongation', 'Avoid concurrent CNS depressants'] },
  { name: 'Morphine', genericName: 'Morphine Sulfate', category: 'Opioid Analgesic', dosages: ['2mg', '5mg', '10mg', '15mg'], routes: ['Oral', 'IV', 'IM', 'Subcutaneous'], sideEffects: ['Respiratory depression', 'Nausea', 'Constipation', 'Dependence'], indications: ['Severe pain', 'Acute pulmonary edema'], contraindications: ['Respiratory depression', 'Paralytic ileus'], nursingConsiderations: ['Monitor respiratory rate and sedation', 'Naloxone is antidote', 'Assess pain regularly'] },
  { name: 'ART-LPV/r', genericName: 'Lopinavir/Ritonavir', category: 'Antiretroviral (HIV)', dosages: ['100/25mg', '200/50mg'], routes: ['Oral'], sideEffects: ['Diarrhea', 'Nausea', 'Hyperlipidemia', 'Hepatotoxicity'], indications: ['HIV infection'], contraindications: ['Severe hepatic impairment'], nursingConsiderations: ['Take with food', 'Monitor liver function and lipid profile', 'Adherence counseling'] },
  { name: 'Iron Dextran', genericName: 'Iron Dextran', category: 'Iron Supplement', dosages: ['100mg', '200mg', '500mg'], routes: ['IV', 'IM'], sideEffects: ['Anaphylaxis', 'Hypotension', 'Pain at injection site'], indications: ['Iron deficiency anemia (severe)', 'Chronic kidney disease'], contraindications: ['Hemochromatosis', 'Iron overload'], nursingConsiderations: ['Give test dose first', 'Monitor for anaphylaxis', 'Use Z-track for IM injection'] },
  { name: 'Dopamine', genericName: 'Dopamine', category: 'Inotropic/Vasopressor', dosages: ['200mg/5mL', '400mg/5mL'], routes: ['IV'], sideEffects: ['Tachycardia', 'Arrhythmias', 'Hypertension', 'Tissue necrosis (extravasation)'], indications: ['Shock', 'Hypotension', 'Heart failure'], contraindications: ['Hypovolemia (correct first)', 'Ventricular fibrillation'], nursingConsiderations: ['Titrate to BP response', 'Monitor IV site for extravasation', 'Use central line if possible'] },
  { name: 'Dexamethasone', genericName: 'Dexamethasone', category: 'Corticosteroid', dosages: ['2mg', '4mg', '8mg', '16mg'], routes: ['Oral', 'IV', 'IM'], sideEffects: ['Hyperglycemia', 'Immunosuppression', 'Weight gain', 'Osteoporosis'], indications: ['Inflammation', 'Cerebral edema', 'COVID-19 severe', 'Preterm labor (fetal lung maturity)'], contraindications: ['Systemic fungal infection'], nursingConsiderations: ['Monitor blood glucose', 'Taper dose gradually', 'Avoid live vaccines'] },
  { name: 'Lignocaine', genericName: 'Lidocaine', category: 'Local Anesthetic/Antiarrhythmic', dosages: ['1%', '2%', '5%'], routes: ['Topical', 'Local infiltration', 'IV'], sideEffects: ['Dizziness', 'Tremor', 'Seizures', 'Cardiac arrest'], indications: ['Local anesthesia', 'Ventricular arrhythmias'], contraindications: ['Heart block', 'Severe bradycardia'], nursingConsiderations: ['Do not exceed maximum dose', 'Use with caution in liver disease', 'Have resuscitation equipment ready'] },
];

export async function getDrugs(req, res) {
  try {
    const { search } = req.query;
    let result = drugs;
    if (search) {
      const q = search.toLowerCase();
      result = drugs.filter(d => d.name.toLowerCase().includes(q) || d.genericName.toLowerCase().includes(q) || d.category.toLowerCase().includes(q));
    }
    res.json(result.slice(0, 50));
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}

export async function getDrugByName(req, res) {
  try {
    const drug = drugs.find(d => d.name.toLowerCase() === req.params.name.toLowerCase());
    if (!drug) return res.status(404).json({ error: 'Drug not found' });
    res.json(drug);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}
